### ISSUE TITLE
error messages after migration / getaddrinfo / Failed to activate any config changes

### ISSUE THREAD

**Issue by MartinM01** [nextcloud/all-in-one#1055]
### Steps to reproduce
1. database and file migration according to instructions
2. docker-compose according to instructions
3. nginx proxy according to instructions
4. öffne nextcloud log (mastercontainer ui)

### Expected behavior 
1. ```getaddrinfo``` should work
2. ```bad gateway error``` should not appear
5. ```Failed to activate any config changes``` should not appear

### Actual behavior 
looks like an error with the nameresolution und after this sequential errors
ping xxxx.xxxx.de/ inside of nexcloud-aio container works
curl https://xxxx.xxxx.de/hosting/discovery inside of nexcloud-aio container works 

### Host OS 
Ubuntu 20.04

#### Nextcloud AIO version 
24.0.4

#### Current channel 
latest

#### Other valuable info 
```
nc: getaddrinfo: Name does not resolve
Waiting for database to start...
              now              
-------------------------------
 2022-08-25 08:00:14.341592+02
(1 row)

Configuring Redis as session handler
Applying one-click-instance settings...
System config value one-click-instance set to boolean true
System config value one-click-instance.user-limit set to integer 100
Adjusting log files...
System config value logfile set to string /var/www/html/data/nextcloud.log
Config value logfile for app admin_audit set to /var/www/html/data/audit.log
Applying network settings...
System config value trusted_domains => 1 set to string xxxx.xxxx.de
System config value overwrite.cli.url set to string https://xxxx.xxxx.de/
System config value htaccess.RewriteBase set to string /
.htaccess has been updated
System config value files_external_allow_create_new_local set to boolean true
System config value trusted_proxies => 0 set to string 127.0.0.1
System config value trusted_proxies => 1 set to string ::1
Config value base_endpoint for app notify_push set to https://xxxx.xxxx.de/push
Config value wopi_url for app richdocuments set to https://xxxx.xxxx.de/
System config value allow_local_remote_servers set to boolean true
Config value stun_servers for app spreed set to ["xxxx.xxxx.de:3478"]
Config value turn_servers for app spreed set to [{"server":"xxxx.xxxx.de:3478","secret":"xxxx","protocols":"udp,tcp"}]
Config value signaling_servers for app spreed set to {"servers":[{"server":"https://xxxx.xxxx.de/standalone-signaling/","verify":true}],"secret":"xxxx"}
Config value av_mode for app files_antivirus set to daemon
Config value av_port for app files_antivirus set to 3310
Config value av_host for app files_antivirus set to nextcloud-aio-clamav
Config value av_stream_max_length for app files_antivirus set to 104857600
Config value av_max_file_size for app files_antivirus set to -1
Config value av_infected_action for app files_antivirus set to only_log
Activating collabora config
[25-Aug-2022 08:00:24] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[25-Aug-2022 08:00:24] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[25-Aug-2022 08:00:24] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[25-Aug-2022 08:00:24] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[25-Aug-2022 08:00:24] NOTICE: fpm is running, pid 265
[25-Aug-2022 08:00:24] NOTICE: ready to handle connections
Failed to activate any config changes
Server error: `GET https://xxxx.xxxx.de/hosting/discovery` resulted in a `502 Bad Gateway` response:
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>ngin (truncated...)

#0 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /var/www/html/3rdparty/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/html/lib/private/Http/Client/Client.php(218): GuzzleHttp\Client->request('get', 'https://nextclo...', Array)
#11 /var/www/html/custom_apps/richdocuments/lib/WOPI/DiscoveryManager.php(84): OC\Http\Client\Client->get('https://nextclo...', Array)
#12 /var/www/html/custom_apps/richdocuments/lib/WOPI/DiscoveryManager.php(56): OCA\Richdocuments\WOPI\DiscoveryManager->fetchFromRemote()
#13 /var/www/html/custom_apps/richdocuments/lib/WOPI/Parser.php(41): OCA\Richdocuments\WOPI\DiscoveryManager->get()
#14 /var/www/html/custom_apps/richdocuments/lib/Command/ActivateConfig.php(70): OCA\Richdocuments\WOPI\Parser->getUrlSrc('Capabilities')
#15 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\RichDocuments\Command\ActivateConfig->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\RichDocuments\Command\ActivateConfig), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/console.php(100): OC\Console\Application->run()
#21 /var/www/html/occ(11): require_once('/var/www/html/c...')
#22 {main}
```

**Comment by szaimen** [comment]
Hi, please try again with v2.0.0 Beta. See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel. Do you still have the same error messages with that or are a few resolved?

**Comment by MartinM01** [comment]
Hi, I will give it a try and get back to you with feedback.

**Comment by MartinM01** [comment]
```
nc: getaddrinfo: Name does not resolve
Waiting for database to start...
              now              
-------------------------------
 2022-08-29 11:43:25.423507+00
(1 row)

Configuring Redis as session handler...
Setting php max children...
System config value tempdirectory set to string /mnt/ncdata/tmp/
Applying one-click-instance settings...
System config value one-click-instance set to boolean true
System config value one-click-instance.user-limit set to integer 100
Adjusting log files...
System config value logfile set to string /var/www/html/data/nextcloud.log
Config value logfile for app admin_audit set to /var/www/html/data/audit.log
Applying network settings...
System config value trusted_domains => 1 set to string xxxx
System config value overwrite.cli.url set to string https://xxxx/
System config value htaccess.RewriteBase set to string /
.htaccess has been updated
System config value files_external_allow_create_new_local set to boolean false
System config value trusted_proxies => 0 set to string 127.0.0.1
System config value trusted_proxies => 1 set to string ::1
Config value base_endpoint for app notify_push set to https://xxxx/push
Config value wopi_url for app richdocuments set to https://xxxx/
System config value allow_local_remote_servers set to boolean true
Config value stun_servers for app spreed set to ["nextcloud.home-server.berlin:3478"]
Config value turn_servers for app spreed set to [{"server":"xxxx:3478","secret":"xxxx","protocols":"udp,tcp"}]
Config value signaling_servers for app spreed set to {"servers":[{"server":"https://xxxx/standalone-signaling/","verify":true}],"secret":"xxxx"}
Config value av_mode for app files_antivirus set to daemon
Config value av_port for app files_antivirus set to 3310
Config value av_host for app files_antivirus set to nextcloud-aio-clamav
Config value av_stream_max_length for app files_antivirus set to 104857600
Config value av_max_file_size for app files_antivirus set to -1
Config value av_infected_action for app files_antivirus set to only_log
System config value enabledPreviewProviders => 0 deleted
System config value preview_imaginary_url deleted
[29-Aug-2022 11:43:36] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[29-Aug-2022 11:43:36] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[29-Aug-2022 11:43:36] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[29-Aug-2022 11:43:36] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[29-Aug-2022 11:43:36] NOTICE: fpm is running, pid 293
[29-Aug-2022 11:43:36] NOTICE: ready to handle connections
Activating collabora config...
Activated any config changes
```

This looks much better.

**Comment by szaimen** [comment]
All right! So can we close this?

**Comment by MartinM01** [comment]
I'm not sure why this happens ```nc: getaddrinfo: name does not resolve```, but it looks like it has no negative impact.

Yes please close this, thanks.

**Comment by szaimen** [comment]
> I'm not sure why this happens `nc: getaddrinfo: name does not resolve`, but it looks like it has no negative impact.

yes, has no impact!

Closing then :)
