### ISSUE TITLE
Slim Application Error: GetConfig(): Return value must be of type array

### ISSUE THREAD

**Issue by rghvdberg** [nextcloud/all-in-one#1211]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. start with docker compose
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest 
    restart: always
    container_name: nextcloud-aio-mastercontainer 
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    ports:
       - 8080:8080
    environment: # Is needed when using any of the options below
        - APACHE_PORT=11000 
```
  caddy running for reverse proxy
```
#Nextcloud
https://<SNIP>:443 { 
	reverse_proxy localhost:11000
}
```

2. Nextcloud AIO setup and login load fine
3. after starting containers I get the error

### Expected behavior 
use nextcloud!

### Actual behavior 
spinner stops and the page seems to return to the previous state
on refreshing the page or pressing the `Start Container` button again I get the error page
```
Slim Application Error

The application could not run because of the following error:
Details
Type: TypeError
Code: 0
Message: AIO\Data\ConfigurationManager::GetConfig(): Return value must be of type array, null returned
File: /var/www/docker-aio/php/src/Data/ConfigurationManager.php
Line: 15
Trace

#0 /var/www/docker-aio/php/src/Data/ConfigurationManager.php(307): AIO\Data\ConfigurationManager->GetConfig()
#1 /var/www/docker-aio/php/src/Controller/DockerController.php(207): AIO\Data\ConfigurationManager->GetDomain()
#2 /var/www/docker-aio/php/public/index.php(72): AIO\Controller\DockerController->StartDomaincheckContainer()
#3 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Closure->{closure}(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#4 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#5 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#7 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#8 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
#9 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(456): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#10 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#11 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#12 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#13 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#14 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#15 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#16 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#17 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#18 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#19 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#20 /var/www/docker-aio/php/public/index.php(164): Slim\App->run()
#21 {main}
```
### Host OS 
Ubuntu 22.04.1 LTS

#### Nextcloud AIO version 
that page won't load no more :man_shrugging: 
#### Current channel 
:man_shrugging: 
#### Other valuable info 
```
docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu4
```

```
caddy version
v2.6.1 h1:EDqo59TyYWhXQnfde93Mmv4FJfYe00dO60zMiEt+pzo=
```

**Comment by szaimen** [comment]
Hi, thanks for your report! This looks like a hickup to me. Can you please try to reset the instance properly and try again afterwards? See https://github.com/nextcloud/all-in-one#how-to-properly-reset-the-instance

**Comment by rghvdberg** [comment]
still errors out
here's what I did

```
docker-compose down 
Stopping nextcloud-aio-mastercontainer ... done
Removing nextcloud-aio-mastercontainer ... done
Removing network nextcloud_default
```

```
docker stop nextcloud-aio-collabora nextcloud-aio-database nextcloud-aio-imaginary nextcloud-aio-redis 
nextcloud-aio-collabora
nextcloud-aio-database
nextcloud-aio-imaginary
nextcloud-aio-redis
```

```
docker ps --filter "status=exited"
CONTAINER ID   IMAGE                              COMMAND                  CREATED       STATUS                      PORTS     NAMES
603eb689a605   nextcloud/aio-imaginary:latest     "/usr/local/bin/imag…"   8 hours ago   Exited (0) 16 seconds ago             nextcloud-aio-imaginary
3a31938409ae   nextcloud/aio-redis:latest         "start.sh"               8 hours ago   Exited (0) 16 seconds ago             nextcloud-aio-redis
a747aab25282   nextcloud/aio-postgresql:latest    "start.sh"               8 hours ago   Exited (0) 16 seconds ago             nextcloud-aio-database
4b9286c2b01e   nextcloud/aio-collabora:latest     "/start-collabora-on…"   8 hours ago   Exited (0) 16 seconds ago             nextcloud-aio-collabora
2b9ae1bec36f   nextcloud/aio-domaincheck:latest   "/start.sh"              8 hours ago   Exited (137) 8 hours ago              nextcloud-aio-domaincheck
```

```
docker container prune
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] y
Deleted Containers:
603eb689a6059f10df539f33c7b79b098e44189f2c5073cdc704bc8fecbd44c0
3a31938409aea87f8d621e8f00615444d5ff73529097435e72965f4e7d027cab
a747aab25282738d1abe1534846fd746cbad4c28c0c3295c2d7bd25e591ec07c
4b9286c2b01eb776fa9f48b66a64a3d92b7942ad02fe92a7336bc83deb290545
2b9ae1bec36f548173b86b40c90eeef4381c0e08453a66227dee23b482df30cd
```
```

docker network rm nextcloud-aio 
nextcloud-aio
```

```
docker volume ls --filter "dangling=true"
DRIVER    VOLUME NAME
local     96d82e13a1567aeeecd2b0e7a7791df3564de67790048026e5e51a22b6779463
local     nextcloud_aio_database
local     nextcloud_aio_database_dump
local     nextcloud_aio_mastercontainer
local     nextcloud_aio_nextcloud
local     nextcloud_aio_nextcloud_data
```

```
docker volume prune
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y 
Deleted Volumes:
nextcloud_aio_mastercontainer
nextcloud_aio_database
nextcloud_aio_database_dump
96d82e13a1567aeeecd2b0e7a7791df3564de67790048026e5e51a22b6779463
nextcloud_aio_nextcloud
nextcloud_aio_nextcloud_data
```

```
docker image prune -a
WARNING! This will remove all images without at least one container associated to them.
Are you sure you want to continue? [y/N] y
Deleted Images:
untagged: nextcloud/all-in-one:latest
untagged: nextcloud/all-in-one@sha256:c4934c32d9de9cf246884dc91254d1f6f3448bfec6499dfbbb7d4c1a6390f338
deleted: sha256:829334051ec97e1dcdb4f11bfdfea044f4f3ebed30acac0178120014478669a2
deleted: sha256:5ce15b01f95277785ac5376ad43544593291576277e2ff453295d6dce8574cf9
.
.
.
deleted: sha256:b45078e74ec97c5e600f6d5de8ce6254094fb3cb4dc5e1cc8335fb31664af66e

Total reclaimed space: 2.636GB
```
I do 'the dance' again, but I get the same error :-(  
containers seem to run fine though

```
docker ps
CONTAINER ID   IMAGE                                   COMMAND                  CREATED              STATUS                        PORTS                                                         NAMES
cfb9722e1d00   nextcloud/aio-imaginary:latest          "/usr/local/bin/imag…"   About a minute ago   Up About a minute (healthy)   9000/tcp                                                      nextcloud-aio-imaginary
5a70a15c7216   nextcloud/aio-redis:latest              "start.sh"               About a minute ago   Up About a minute (healthy)   6379/tcp                                                      nextcloud-aio-redis
bfa1f5b64a89   nextcloud/aio-postgresql:latest         "start.sh"               About a minute ago   Up About a minute (healthy)   5432/tcp                                                      nextcloud-aio-database
8c2df031e6e2   nextcloud/aio-collabora:latest          "/start-collabora-on…"   About a minute ago   Up About a minute (healthy)   9980/tcp                                                      nextcloud-aio-collabora
0de4970dc0fa   nextcloud/all-in-one:latest             "start.sh /usr/bin/s…"   6 minutes ago        Up 6 minutes (healthy)        80/tcp, 8443/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   nextcloud-aio-mastercontainer
```

ftr, on my local machine (ubuntu 20.04) everything works fine

**Comment by rghvdberg** [comment]
hold on ,
apache and nextcloud containers aren't running :thinking:

**Comment by szaimen** [comment]
Hm... Can you try again another time and post the complete mastercontainer logs here after the initial error appeard? Thanks!

**Comment by rghvdberg** [comment]
hmmm  I got an eerie feeling this is just a matter of a full disk
had some other things running that complained about disk full 

if you want you can close this ..

**Comment by szaimen** [comment]
Oh, that explain things. Thanks!
