### ISSUE TITLE
Nextcloud Office not working

### ISSUE THREAD

**Issue by mighty-services** [nextcloud/all-in-one#1561]
Thanks for all your work, guys! I'm really enjoying this project :)

I just switched from latest to beta, so that I have the latest and greatest Nextcloud Hub3 version on my server :)

After the upgrade, I realized that Nextcloud Office is not working anymore. It did when I set up this instance a few months ago with Nextcloud 24. In the Setup-Screen, it says the there is no connection possible. I've put in the URL of my instance, so https://cloud.example.com

I don't know If I need to add something behind that. I couldn't find any information regarding to this in the internet.

The things I tried so far (with no success):
  - switching off ufw firewall
  - changing to host-mode-network
  - stopping all containers, issuing `docker system prune` and rebuilding it all with `docker-compose up`
  - stopping all containers, issuing `docker system prune`, removing volumes of apache, collabora, clamav, elasticsearch and rebuilding it all with `docker-compose up`
  - checking all settings of my nginx reverse-proxy
  - checking the hosts-file and the network-settings

When I switch to the collabora demo server it says "OK" in the settings, but when I try to open a document it's telling me that It can open the connection.

What I did before the error:
  - change the IP-Address of the virtual machine (I'm about to separate/secure my network)
  - enabling ufw firewall with open ports for 80, 8080 and 8443

Nextcloud AIO is on the latest version (mastercontainer has version 4.0) and it's running in an up-to-date Ubuntu 22.04 vm with this config:
![grafik](https://user-images.githubusercontent.com/71066192/208761460-39d96d3a-873e-4b36-997b-af11c2372e33.png)

**Comment by mighty-services** [comment]
that's the log from the master container:

```
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 118
WARNING: the devicemapper storage-driver is deprecated, and will be removed in a future release.
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
[0;92mInitial startup of Nextcloud All In One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080

If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443[0m
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.2. Set the 'ServerName' directive globally to suppress this message
[Tue Dec 20 20:15:01.379836 2022] [ssl:warn] [pid 121] AH01906: 172.20.0.2:8080:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Dec 20 20:15:01.379889 2022] [ssl:warn] [pid 121] AH01909: 172.20.0.2:8080:0 server certificate does NOT include an ID which matches the server name
{"level":"info","ts":1671567301.3816109,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
{"level":"warn","ts":1671567301.3838482,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/Caddyfile","line":2}
{"level":"info","ts":1671567301.3850005,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"warn","ts":1671567301.3852391,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
{"level":"warn","ts":1671567301.3852522,"logger":"http","msg":"automatic HTTP->HTTPS redirects are disabled","server_name":"srv1"}
{"level":"info","ts":1671567301.3856926,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0001f28c0"}
{"level":"warn","ts":1671567301.3857899,"logger":"tls","msg":"YOUR SERVER MAY BE VULNERABLE TO ABUSE: on-demand TLS is enabled, but no protections are in place","docs":"https://caddyserver.com/docs/automatic-https#on-demand-tls"}
{"level":"info","ts":1671567301.3864424,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/docker-aio-config/caddy/"}
{"level":"info","ts":1671567301.386468,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1671567301.3864498,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1671567301.3865538,"logger":"http","msg":"enabling HTTP/3 listener","addr":":8443"}
{"level":"info","ts":1671567301.386824,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details."}
{"level":"info","ts":1671567301.3869948,"logger":"http.log","msg":"server running","name":"srv1","protocols":["h1","h2","h3"]}
{"level":"error","ts":1671567301.3870358,"msg":"unable to create folder for config autosave","dir":"/root/.config/caddy","error":"mkdir /root/.config: permission denied"}
{"level":"info","ts":1671567301.387044,"msg":"serving initial configuration"}
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.2. Set the 'ServerName' directive globally to suppress this message
[Tue Dec 20 20:15:01.403537 2022] [ssl:warn] [pid 121] AH01906: 172.20.0.2:8080:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Dec 20 20:15:01.403554 2022] [ssl:warn] [pid 121] AH01909: 172.20.0.2:8080:0 server certificate does NOT include an ID which matches the server name
[Tue Dec 20 20:15:01.405591 2022] [mpm_prefork:notice] [pid 121] AH00163: Apache/2.4.54 (Debian) PHP/8.0.26 OpenSSL/1.1.1n configured -- resuming normal operations
[Tue Dec 20 20:15:01.405729 2022] [core:notice] [pid 121] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Comment by szaimen** [comment]
Hm... Can you follow https://github.com/nextcloud/all-in-one/discussions/1358?

**Comment by mighty-services** [comment]
thanks for the quick reply, here´s the output of the Collabora (Nextcloud Office) part:
```
bash-5.1# curl -vvv https://$NC_DOMAIN:443/hosting/discovery
*   Trying 111.111.111.111:443...

* connect to 111.111.111.111 port 443 failed: Operation timed out
* Failed to connect to cloud.it-mighty.de port 443 after 131149 ms: Operation timed out
* Closing connection 0
```

I replaced the IP-Address of course.

**Comment by mighty-services** [comment]
that´s the screen of nextcloud office setup in my instance:
![grafik](https://user-images.githubusercontent.com/71066192/208766080-cca65931-3298-4a45-985c-5d25adcec84d.png)

**Comment by mighty-services** [comment]
and that´s the logfile of the nextcloud-container (I replaced sensitive information of course):
```
              now              
-------------------------------
 2022-12-20 20:15:42.674681+00
(1 row)

Installing imagemagick via apk...
Installing PHP build dependencies...
Installing Imagick via PECL...
Configuring Redis as session handler...
Setting php max children...
System config value tempdirectory set to string /mnt/ncdata/tmp/
Applying one-click-instance settings...
System config value one-click-instance set to boolean true
System config value one-click-instance.user-limit set to integer 100
System config value one-click-instance.link set to string https://nextcloud.com/all-in-one/
support already enabled
Adjusting log files...
System config value logfile set to string /var/www/html/data/nextcloud.log
Config value logfile for app admin_audit set to /var/www/html/data/audit.log
Applying network settings...
System config value trusted_domains => 1 set to string cloud.example.com
System config value overwrite.cli.url set to string https://cloud.iexample.com/
System config value htaccess.RewriteBase set to string /
.htaccess has been updated
System config value files_external_allow_create_new_local set to boolean true
System config value trusted_proxies => 0 set to string 127.0.0.1
System config value trusted_proxies => 1 set to string ::1
Config value base_endpoint for app notify_push set to https://cloud.example.com/push
Config value wopi_url for app richdocuments set to https://cloud.example.com/
System config value allow_local_remote_servers set to boolean true
Config value av_mode for app files_antivirus set to daemon
Config value av_port for app files_antivirus set to 3310
Config value av_host for app files_antivirus set to nextcloud-aio-clamav
Config value av_stream_max_length for app files_antivirus set to 104857600
Config value av_max_file_size for app files_antivirus set to -1
Config value av_infected_action for app files_antivirus set to only_log
System config value enabledPreviewProviders => 0 set to string OC\Preview\Imaginary
System config value preview_imaginary_url set to string http://nextcloud-aio-imaginary:9000
{
    "search_platform": "OCA\\FullTextSearch_Elasticsearch\\Platform\\ElasticSearchPlatform",
    "app_navigation": "0",
    "provider_indexed": "{\"test_provider\":\"0\",\"deck\":\"1\",\"files\":\"1\"}",
    "cron_err_reset": "1670836141",
    "tick_ttl": "1800",
    "collection_indexing_list": "50",
    "migration_24": "1"
}
{
    "elastic_host": "http:\/\/nextcloud-aio-fulltextsearch:9200",
    "elastic_index": "nextcloud-aio",
    "fields_limit": "10000",
    "es_ver_below66": "0",
    "analyzer_tokenizer": "standard"
}
{
    "files_local": "1",
    "files_external": "0",
    "files_group_folders": "0",
    "files_encrypted": "0",
    "files_federated": "0",
    "files_size": "20",
    "files_pdf": "1",
    "files_office": "1",
    "files_image": "0",
    "files_audio": "0"
}
[20-Dec-2022 21:58:13] NOTICE: fpm is running, pid 3990
[20-Dec-2022 21:58:13] NOTICE: ready to handle connections

```

**Comment by szaimen** [comment]
`111.111.111.111` hm... Where does this ip-address come from? Is it the public ip-address of your server?

**Comment by mighty-services** [comment]
no its the replacement

**Comment by mighty-services** [comment]
there was the correct public ip-address of my internet-connection, but i replaced it

**Comment by mighty-services** [comment]
that the nging reverse-proxy config:
![grafik](https://user-images.githubusercontent.com/71066192/208766789-260bffa1-4908-4bc8-a90e-996d2dc0eb75.png)

![grafik](https://user-images.githubusercontent.com/71066192/208766822-599ba100-b492-4d69-81de-294820f0f03f.png)

![grafik](https://user-images.githubusercontent.com/71066192/208766853-408a4f57-c4a0-4474-9fbb-327603a4eabd.png)

![grafik](https://user-images.githubusercontent.com/71066192/208766883-fc24e443-10f4-44a9-ab5f-c17ac55167a2.png)

**Comment by mighty-services** [comment]
in the nextloud instance there are a lot of this errors here about the office-app:
![grafik](https://user-images.githubusercontent.com/71066192/208767275-f33132c1-5e53-49d0-89b7-03e7fdcc28a8.png)

**Comment by mighty-services** [comment]
and thats throwing several time, when i run the mastercontainer in the foregroud:
```
nextcloud-aio-mastercontainer | [Tue Dec 20 20:14:11.845912 2022] [php:notice] [pid 195] [client 127.0.0.1:34288] 404 Not Found\nType: Slim\\Exception\\HttpNotFoundException\nCode: 404\nMessage: Not found.\nFile: /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php\nLine: 76\nTrace: #0 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(56): Slim\\Middleware\\RoutingMiddleware->performRouting(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#1 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(476): Slim\\Routing\\RouteRunner->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#2 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\\Csrf\\Guard->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Slim\\Routing\\RouteRunner))\n#3 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#4 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\\Views\\TwigMiddleware->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#5 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\\Middleware\\AuthMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#7 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#8 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\\Middleware\\ErrorMiddleware->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#9 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#10 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\\MiddlewareDispatcher->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#11 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\\App->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#12 /var/www/docker-aio/php/public/index.php(167): Slim\\App->run()\n#13 {main}, referer: https://172.16.2.111:8080/containers
```

**Comment by mighty-services** [comment]
I hope this information helps

**Comment by szaimen** [comment]
I am sorry but I cannot reproduce your office connection issue. Running the [debug command](https://github.com/nextcloud/all-in-one/discussions/1358) clearly revelealed that something is incorrectly configured in your network. So you need to find out what the cause of it is and how you can fix it. 

As I cannot reproduce the issue (I even tried to reproduce it in my home network and it works here without any problem), I'll move this to discussions.
