### ISSUE TITLE
Recognize not able to detect if host supports native TensorFlow operation. 

### ISSUE THREAD

**Issue by Sid127** [nextcloud/all-in-one#1806]
### Steps to reproduce
1. Install/enable Recognize app if not already enabled
2. Head to Administration Settings > Recognize
3. Attempt to configure

### Expected behavior 
The app can detect if the host supports native TensorFlow (avx instruction set)
### Actual behavior 
![image](https://user-images.githubusercontent.com/20684727/213367448-8443cbf9-c73a-4517-a643-4ee6164b701a.png)

### Host OS 
Arch Linux

#### Nextcloud AIO version 
5.1.0
#### Current channel 
latest
#### Other valuable info 
mastercontainer logs:
```
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 968
[0;92mInitial startup of Nextcloud All In One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080

If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443[0m
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Jan 16 06:51:25.447527 2023] [ssl:warn] [pid 117] AH01906: 172.17.0.2:8080:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Jan 16 06:51:25.447582 2023] [ssl:warn] [pid 117] AH01909: 172.17.0.2:8080:0 server certificate does NOT include an ID which matches the server name
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Jan 16 06:51:25.479581 2023] [ssl:warn] [pid 117] AH01906: 172.17.0.2:8080:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Jan 16 06:51:25.479603 2023] [ssl:warn] [pid 117] AH01909: 172.17.0.2:8080:0 server certificate does NOT include an ID which matches the server name
{"level":"info","ts":1673851885.4800875,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
{"level":"warn","ts":1673851885.4817715,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/Caddyfile","line":2}
{"level":"info","ts":1673851885.482511,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"warn","ts":1673851885.4826818,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
{"level":"warn","ts":1673851885.4826922,"logger":"http","msg":"automatic HTTP->HTTPS redirects are disabled","server_name":"srv1"}
{"level":"info","ts":1673851885.4833643,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1673851885.483416,"logger":"http","msg":"enabling HTTP/3 listener","addr":":8443"}
{"level":"info","ts":1673851885.4839935,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details."}
{"level":"info","ts":1673851885.4840913,"logger":"http.log","msg":"server running","name":"srv1","protocols":["h1","h2","h3"]}
{"level":"warn","ts":1673851885.4840994,"logger":"tls","msg":"YOUR SERVER MAY BE VULNERABLE TO ABUSE: on-demand TLS is enabled, but no protections are in place","docs":"https://caddyserver.com/docs/automatic-https#on-demand-tls"}
{"level":"error","ts":1673851885.4841363,"msg":"unable to create folder for config autosave","dir":"/root/.config/caddy","error":"mkdir /root/.config: permission denied"}
{"level":"info","ts":1673851885.484144,"msg":"serving initial configuration"}
{"level":"info","ts":1673851885.4841688,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/docker-aio-config/caddy/"}
{"level":"info","ts":1673851885.4852412,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000562f50"}
[Mon Jan 16 06:51:25.486085 2023] [mpm_prefork:notice] [pid 117] AH00163: Apache/2.4.54 (Debian) PHP/8.1.13 OpenSSL/1.1.1n configured -- resuming normal operations
[Mon Jan 16 06:51:25.486111 2023] [core:notice] [pid 117] AH00094: Command line: 'apache2 -D FOREGROUND'
{"level":"info","ts":1673851885.48685,"logger":"tls","msg":"finished cleaning storage units"}
Total reclaimed space: 0B
{"level":"info","ts":1673938285.4966867,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/docker-aio-config/caddy/"}
{"level":"info","ts":1673938285.51647,"logger":"tls","msg":"finished cleaning storage units"}
Total reclaimed space: 0B
{"level":"info","ts":1674024685.4931273,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/docker-aio-config/caddy/"}
{"level":"info","ts":1674024685.4957974,"logger":"tls","msg":"finished cleaning storage units"}
Total reclaimed space: 0B
Deleting duplicate sessions

n 19 06:03:01.516450 2023] [php:notice] [pid 413870] [client 127.0.0.1:52200] 404 Not Found\nType: Slim\\Exception\\HttpNotFoundException\nCode: 404\nMessage: Not found.\nFile: /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php\nLine: 76\nTrace: #0 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(56): Slim\\Middleware\\RoutingMiddleware->performRouting(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#1 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(476): Slim\\Routing\\RouteRunner->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#2 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\\Csrf\\Guard->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Slim\\Routing\\RouteRunner))\n#3 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#4 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\\Views\\TwigMiddleware->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#5 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\\Middleware\\AuthMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#7 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#8 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\\Middleware\\ErrorMiddleware->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#9 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#10 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\\MiddlewareDispatcher->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#11 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\\App->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#12 /var/www/docker-aio/php/public/index.php(170): Slim\\App->run()\n#13 {main}, referer: https://198.244.251.96:8080/api/docker/logs?id=nextcloud-aio-nextcloud
```

nextcloud logs:
```
               now                
----------------------------------
 2023-01-16 12:25:06.888477+05:30
(1 row)

+ '[' -f /dev-dri-group-was-added ']'
++ find /dev -maxdepth 1 -mindepth 1 -name dri
+ '[' -n '' ']'
+ set +x
Installing imagemagick via apk...
Enabling Imagick...
Configuring Redis as session handler...
Setting php max children...
System config value tempdirectory set to string /mnt/ncdata/tmp/
Applying one-click-instance settings...
System config value one-click-instance set to boolean true
System config value one-click-instance.user-limit set to integer 100
System config value one-click-instance.link set to string https://nextcloud.com/all-in-one/
support already enabled
Adjusting log files...
System config value logfile set to string /var/www/html/data/nextcloud.log
Config value logfile for app admin_audit set to /var/www/html/data/audit.log
Applying network settings...
System config value trusted_domains => 1 set to string cloud.sloughland.dev
System config value overwrite.cli.url set to string https://cloud.sloughland.dev/
System config value htaccess.RewriteBase set to string /
.htaccess has been updated
System config value files_external_allow_create_new_local set to boolean false
System config value trusted_proxies => 0 set to string 127.0.0.1
System config value trusted_proxies => 1 set to string ::1
Config value base_endpoint for app notify_push set to https://cloud.sloughland.dev/push
System config value enabledPreviewProviders => 0 deleted
System config value preview_imaginary_url deleted
[16-Jan-2023 12:25:17] NOTICE: fpm is running, pid 210
[16-Jan-2023 12:25:17] NOTICE: ready to handle connections
[16-Jan-2023 12:38:03] WARNING: [pool www] server reached max_children setting (78), consider raising it
[16-Jan-2023 12:55:39] WARNING: [pool www] server reached max_children setting (78), consider raising it
[2023-01-19 11:09:43.750012 +05:30] WARN [notify_push::connection] src/connection.rs:75: WebSocket protocol error: Connection reset without closing handshake
```

apache logs:
```
nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9000: Name or service not known
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message
{"level":"info","ts":1673852120.0467458,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
{"level":"warn","ts":1673852120.048615,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/Caddyfile","line":2}
{"level":"info","ts":1673852120.0496864,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"warn","ts":1673852120.0499835,"logger":"http","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
{"level":"info","ts":1673852120.0501165,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0006b8a80"}
{"level":"info","ts":1673852120.0509593,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/data/caddy"}
{"level":"info","ts":1673852120.0513124,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1673852120.0516365,"msg":"autosaved config (load with --resume flag)","file":"/var/www/.config/caddy/autosave.json"}
{"level":"info","ts":1673852120.0516489,"msg":"serving initial configuration"}
{"level":"info","ts":1673852120.0540452,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"error","ts":1673852131.4135532,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
{"level":"error","ts":1673852951.940348,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"write tcp 172.17.0.6:11000->172.17.0.1:43384: write: broken pipe"}
{"level":"info","ts":1673938520.0516326,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/data/caddy"}
{"level":"info","ts":1673938520.0536244,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1674024920.0594857,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/data/caddy"}
{"level":"info","ts":1674024920.0601797,"logger":"tls","msg":"finished cleaning storage units"}
```

**Comment by Sid127** [comment]
Duplicate of https://github.com/nextcloud/recognize/issues/609
