### ISSUE TITLE
*CRITICAL* - Reinstall failing nextcloud-beta

### ISSUE THREAD

**Issue by FlattusBlastus** [nextcloud/all-in-one#2212]
2023-03-26 06:09:56 permissions_overwrite 0.1.9 installed
2023-03-26 06:09:56 permissions_overwrite enabled
2023-03-26 06:09:56 An unhandled exception has been thrown:
2023-03-26 06:09:56 OCP\AppFramework\QueryException: Could not resolve OCA\Files_External\Service\GlobalStoragesService! Class "OCA\Files_External\Service\GlobalStoragesService" does not exist in /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php:122
2023-03-26 06:09:56 Stack trace:
2023-03-26 06:09:56 #0 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Files_Exter...')
2023-03-26 06:09:56 #1 /var/www/html/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Files_Exter...', true)
2023-03-26 06:09:56 #2 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\ServerContainer->query('OCA\\Files_Exter...', true)
2023-03-26 06:09:56 #3 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
2023-03-26 06:09:56 #4 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map(Object(Closure), Array)
2023-03-26 06:09:56 #5 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
2023-03-26 06:09:56 #6 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Permissions...')
2023-03-26 06:09:56 #7 /var/www/html/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Permissions...', true)
2023-03-26 06:09:56 #8 /var/www/html/lib/private/Console/Application.php(220): OC\ServerContainer->query('OCA\\Permissions...')
2023-03-26 06:09:56 #9 /var/www/html/lib/private/Console/Application.php(130): OC\Console\Application->loadCommandsFromInfoXml(Array)
2023-03-26 06:09:56 #10 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023-03-26 06:09:56 #11 /var/www/html/occ(11): require_once('/var/www/html/c...')
2023-03-26 06:09:56 #12 {main}
2023-03-26 06:09:56 
2023-03-26 06:09:56 Next OCP\AppFramework\QueryException: Could not resolve storagesService! Class "storagesService" does not exist in /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php:102
2023-03-26 06:09:56 Stack trace:
2023-03-26 06:09:56 #0 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
2023-03-26 06:09:56 #1 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map(Object(Closure), Array)
2023-03-26 06:09:56 #2 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
2023-03-26 06:09:56 #3 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Permissions...')
2023-03-26 06:09:56 #4 /var/www/html/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Permissions...', true)
2023-03-26 06:09:56 #5 /var/www/html/lib/private/Console/Application.php(220): OC\ServerContainer->query('OCA\\Permissions...')
2023-03-26 06:09:56 #6 /var/www/html/lib/private/Console/Application.php(130): OC\Console\Application->loadCommandsFromInfoXml(Array)
2023-03-26 06:09:56 #7 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023-03-26 06:09:56 #8 /var/www/html/occ(11): require_once('/var/www/html/c...')
2023-03-26 06:09:56 #9 {main}
2023-03-26 06:09:56 
2023-03-26 06:09:56 Next Exception: Failed to construct console command 'OCA\PermissionsOverwrite\Command\SetCommand': Could not resolve storagesService! Class "storagesService" does not exist in /var/www/html/lib/private/Console/Application.php:226
2023-03-26 06:09:56 Stack trace:
2023-03-26 06:09:56 #0 /var/www/html/lib/private/Console/Application.php(130): OC\Console\Application->loadCommandsFromInfoXml(Array)
2023-03-26 06:09:56 #1 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023-03-26 06:09:56 #2 /var/www/html/occ(11): require_once('/var/www/html/c...')
2023-03-26 06:09:57 #3 {main}An unhandled exception has been thrown:
2023-03-26 06:09:57 OCP\AppFramework\QueryException: Could not resolve OCA\Files_External\Service\GlobalStoragesService! Class "OCA\Files_External\Service\GlobalStoragesService" does not exist in /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php:122

**Comment by Zoey2936** [comment]
please fill out the issue template

**Comment by FlattusBlastus** [comment]
Sorry for the sky is falling response. Removed permissions_overwrite from startup apps. Install proceeding normally.
