### ISSUE TITLE
PHP 404 Not Found when using reverse proxy install

### ISSUE THREAD

**Issue by net47** [nextcloud/all-in-one#2347]
### Steps to reproduce
When using the reverse proxy installation:

```
docker run -d \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 8080:8080 \
-e APACHE_PORT=11000 \
-e APACHE_IP_BINDING=0.0.0.0 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
-e SKIP_DOMAIN_VALIDATION=true \
-e NEXTCLOUD_DATADIR="/root/data" \
nextcloud/all-in-one:latest
```
after setting the domain and timezone, all containers beside Apache and Nextcloud get started. The master container logs are:

```
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 998
WARNING: Support for cgroup v2 is experimental
......+...+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*......+...............+....+......+........+......+.........+.+.....+....+..+.+...+.................+...+.+......+........+.+......+...+..+...+..........+..+....+...+.....+.+..............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+...+..+...+......+.+....................+.............+........+.......+........+.......+...+....................+....+...+.....+...+...+.......+...+..+...+....+...+..+...............+......+.+......+..+............+...+.......+.....+....+..+...+............+...+.......+.....+.........+..........+.............................+.+...+..+..........+...........+...+......+.........+.+...+..+......+.........+.+.................+.+.....+.+........+......+....+.....+.+......+..............+.+........+...+.........+....+.........+...+...+......+.....+....+.........+............+.....+.........+......+....+...........+...............+....+..+.........+...+..........+...............+......+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..+....+......+...............+............+..+...+....+.........+..+...+....+..+....+..+.........+...+.+......+...+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+.........+....+.....+............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+.......+...+..........................+.....................+....+.....+.......+........+....+..+...+......+.+..........................+......................+.....+.+..+...................+..............+.+...+.....+......+.+.....+.+...+.....+.+........+...+...+...............+.........+............+...+..........+...+.....+.............+...........+.+...+.........+...+...............+........+....+......+...........+....+.....+.+.........+.....+.......+...+......+........+.+...........+......+.........+.....................+............+...+...+.+......+.......................+.......+...+.....................+......+........+....+...+.........+.....+................+..................+.....+..........+.....+.......+........+....+...........+.........+.+..+....+..............+.......+...+..+.........+.+..+.............+........+............+.........+......+.......+..+...+..........+..+...+................+.........+....................+.+...........+......+.........+......+..........+.....+.........+...+...............+............+...+.+..............+.+.....................+.....+......+...+............+....+........+......+.......+.....+...+..........+......+.....+...+...+...+....+.....+......+.......+...+..+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
Initial startup of Nextcloud All In One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080

If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443
{"level":"info","ts":1681563280.9426684,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
[15-Apr-2023 12:54:40] NOTICE: fpm is running, pid 122
[15-Apr-2023 12:54:40] NOTICE: ready to handle connections
NOTICE: PHP message: 404 Not Found
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 76
Trace: #0 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(56): Slim\Middleware\RoutingMiddleware->performRouting(Object(GuzzleHttp\Psr7\ServerRequest))
#1 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(476): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#2 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#3 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#4 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#5 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#7 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#8 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#9 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#10 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#11 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#12 /var/www/docker-aio/php/public/index.php(170): Slim\App->run()
#13 {main}
```

### Expected behavior
Apache and Nextcloud container should start, like when using the docker command without the reverse proxy specifics. 

### Actual behavior
Apache and Nextcloud container are not starting due to error message.

### Host OS 
Debian 11 as plain VM in Proxmox (no LXC)
Linux docker-dmz 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

#### Nextcloud AIO version
4.8.1

#### Current channel
latest

**Comment by net47** [comment]
Ok, works now. For everyone having the same issue: just wait, it fixes by itself...
