### ISSUE TITLE
BorgBackupPath

### ISSUE THREAD

**Issue by GUNT0815** [nextcloud/all-in-one#2367]
I run Nextcloud-AIO on Unraid. All works fine. But when I tried to update from v4.7.0 to the next version borg-backup failed.

Borgbackup log:
```
-------------------------------------------------------------
Performing backup...
Starting the backup...
Creating archive at "/mnt/borgbackup/borg::20230417_113103-nextcloud-aio"
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1453, in get_fd
    ts, fd = self.fds[segment]
  File "/usr/lib/python3.10/site-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 291

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5159, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5090, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 675, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 642, in create_inner
    str(cache),
  File "/usr/lib/python3.10/site-packages/borg/cache.py", line 418, in __str__
    return self.str_format.format(self.format_tuple())
  File "/usr/lib/python3.10/site-packages/borg/cache.py", line 445, in format_tuple
    stats = self.stats()
  File "/usr/lib/python3.10/site-packages/borg/cache.py", line 435, in stats
    archive = Archive(self.repository, self.key, self.manifest, archive_name,
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 486, in __init__
    self.load(info.id)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 497, in load
    self.metadata = self._load_meta(self.id)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 489, in _load_meta
    data = self.key.decrypt(id, self.repository.get(id))
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1203, in get
    return self.io.read(segment, offset, id)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1569, in read
    fd = self.get_fd(segment)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1455, in get_fd
    fd = open_fd()
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1436, in open_fd
    fd = open(self.segment_filename(segment), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/borgbackup/borg/data/0/291'
...
-------------------------------------------------------------
```

So I checked what path is configured for borg to backup to in the configuration.json:

-------------------------------------------------------------
"borg_backup_host_location": "/mnt/user/archive/nextcloud-borgbackup",
-------------------------------------------------------------

And also the nextcloud-aio webui shows:

--------------------------------------------
The backup itself will use a tool that is called [BorgBackup](https://github.com/borgbackup/borg#what-is-borgbackup) which is a well-known server backup tool that efficiently backs up your files and encrypts them on the fly.

Backups get created in the following directory on the host: /mnt/user/archive/nextcloud-borgbackup/borg
---------------------------------------------

So I checked in the console if the path really exists - yes, it is there and it and its subfolrder belong to root.

How can I get the borgbackup back to work? Do I have to change the owner of the folder?

**Comment by szaimen** [comment]
Hi, can you do an inregrity check of the backup?
