### ISSUE TITLE
Permission denied (13) in /var/www/docker-aio/php/public/index.php on line 43

### ISSUE THREAD

**Issue by Timmmy** [nextcloud/all-in-one#32]
Hi all,

I'm getting the error below when starting the container using the provided instructions.
Any ideas?

Thanks in advance,

Tim

```

Warning: session_start(): open(/mnt/docker-aio-config/session//sess_de4bea132c31c531df8bfa926227e620, O_RDWR) failed: Permission denied (13) in /var/www/docker-aio/php/public/index.php on line 43

Warning: session_start(): Failed to read session data: files (path: /mnt/docker-aio-config/session/) in /var/www/docker-aio/php/public/index.php on line 43

Fatal error: Uncaught RuntimeException: Invalid CSRF storage. Use session_start() before instantiating the Guard middleware or provide array storage. in /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php:139 Stack trace: #0 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(113): Slim\Csrf\Guard->setStorage(NULL) #1 /var/www/docker-aio/php/public/index.php(37): Slim\Csrf\Guard->__construct(Object(Http\Factory\Guzzle\ResponseFactory)) #2 [internal function]: {closure}() #3 /var/www/docker-aio/php/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Object(Closure), Array) #4 /var/www/docker-aio/php/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call(Object(Closure), Array) #5 /var/www/docker-aio/php/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve(Object(DI\Definition\FactoryDefinition), Array) #6 /var/www/docker-aio/php/vendor/php-di/php-di/src/Container.php(387): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\FactoryDefinition), Array) #7 /var/www/docker-aio/php/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition(Object(DI\Definition\FactoryDefinition)) #8 /var/www/docker-aio/php/public/index.php(49): DI\Container->get('Slim\\Csrf\\Guard') #9 {main} thrown in /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php on line 139
```

**Comment by szaimen** [comment]
Hi, did you make sure to use the correct command to create the container?
Maybe you didn't mount the directory inside a volume but on a directory?
Can you please post the excact command here that you used? Thanks!

**Comment by szaimen** [comment]
It looks like the server is not able to write to the /mnt/docker-aio-config/session/ directory. So this is likely a permission issue. Since we check permissioins during the container start here https://github.com/nextcloud/all-in-one/blob/13360b176e58deca026e8a190ab221131ac96549/Containers/mastercontainer/start.sh#L19 I don't think this will be a huge problem. I'll leave this open for now.

**Comment by szaimen** [comment]
should be resolved with the latest image release.
