### ISSUE TITLE
Talk Recording not working

### ISSUE THREAD

**Issue by y4my4my4m** [nextcloud/all-in-one#3267]
### Steps to reproduce
1. Install Nextcloud AIO v27
2. Install Talk and Talk recording from the AIO dashboard
3. Start talk and attempt to start a recording

### Expected behavior 

Should record

### Actual behavior 
```
ERROR:nextcloud.talk.recording.Service-https://MYWEBSITE.com/-e84eo65e:Error when disconnecting from signaling server                                       
Traceback (most recent call last):                                                                                                                              
  File "/usr/local/lib/python3.11/site-packages/nextcloud/talk/recording/Service.py", line 195, in start                                                        
    self._participant.joinCall(self.token)                                                                                                                      
  File "/usr/local/lib/python3.11/site-packages/nextcloud/talk/recording/Participant.py", line 451, in joinCall                                                 
    settings = self.seleniumHelper.executeAsync(f'''                                                                                                            
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                            
  File "/usr/local/lib/python3.11/site-packages/nextcloud/talk/recording/Participant.py", line 379, in executeAsync                                             
    result = self.driver.execute_async_script(script)                                                                                                           
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute_async_script                                      
    return self.execute(command, {"script": script, "args": converted_args})["value"]                                                                           
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                    
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute                                                   
    self.error_handler.check_response(response)                                                                                                                 
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: WebDriver session does not exist, or is not active
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:187:5
InvalidSessionIDError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:442:5
assert.that/<@chrome://remote/content/shared/webdriver/Assert.sys.mjs:485:13
assert.session@chrome://remote/content/shared/webdriver/Assert.sys.mjs:37:4
despatch@chrome://remote/content/marionette/server.sys.mjs:317:19
execute@chrome://remote/content/marionette/server.sys.mjs:291:16
onPacket/<@chrome://remote/content/marionette/server.sys.mjs:264:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:265:9
_onJSONObjectReady/<@chrome://remote/content/marionette/transport.sys.mjs:496:20 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nextcloud/talk/recording/Service.py", line 299, in _stopHelpers
    self._participant.disconnect()
  File "/usr/local/lib/python3.11/site-packages/nextcloud/talk/recording/Participant.py", line 480, in disconnect
    self.seleniumHelper.execute('''
  File "/usr/local/lib/python3.11/site-packages/nextcloud/talk/recording/Participant.py", line 308, in execute
    result = self.driver.execute_script(script)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 405, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: WebDriver session does not exist, or is not active
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:187:5
InvalidSessionIDError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:442:5
assert.that/<@chrome://remote/content/shared/webdriver/Assert.sys.mjs:485:13
assert.session@chrome://remote/content/shared/webdriver/Assert.sys.mjs:37:4
despatch@chrome://remote/content/marionette/server.sys.mjs:317:19
execute@chrome://remote/content/marionette/server.sys.mjs:291:16
onPacket/<@chrome://remote/content/marionette/server.sys.mjs:264:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:265:9
_onJSONObjectReady/<@chrome://remote/content/marionette/transport.sys.mjs:496:20

ERROR:nextcloud.talk.recording.Server:Failed to start recording: https://MYWEBSITE.com/ e84eo65e
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nextcloud/talk/recording/Server.py", line 170, in _startRecordingService
    service.start(actorType, actorId)
  File "/usr/local/lib/python3.11/site-packages/nextcloud/talk/recording/Service.py", line 195, in start
    self._participant.joinCall(self.token)
  File "/usr/local/lib/python3.11/site-packages/nextcloud/talk/recording/Participant.py", line 451, in joinCall
    settings = self.seleniumHelper.executeAsync(f'''
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nextcloud/talk/recording/Participant.py", line 379, in executeAsync
    result = self.driver.execute_async_script(script)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute_async_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: WebDriver session does not exist, or is not active
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:187:5
InvalidSessionIDError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:442:5
assert.that/<@chrome://remote/content/shared/webdriver/Assert.sys.mjs:485:13
assert.session@chrome://remote/content/shared/webdriver/Assert.sys.mjs:37:4
despatch@chrome://remote/content/marionette/server.sys.mjs:317:19
execute@chrome://remote/content/marionette/server.sys.mjs:291:16
onPacket/<@chrome://remote/content/marionette/server.sys.mjs:264:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:265:9
_onJSONObjectReady/<@chrome://remote/content/marionette/transport.sys.mjs:496:20
```

### Host OS 
Operating System: Linux 4.4.0-103-generic x86_64
CPU: Intel(R) Xeon(R) CPU D-1521 @ 2.40GHz (4 cores)
Memory: 4.84 GB
Server time: Mon Aug 28 00:50:47 EDT 2023
Uptime: 12 days, 13 hours, 21 minutes, 22 seconds

#### Nextcloud AIO version 
v7.0.0
#### Current channel 
Latest Channel
#### Other valuable info 
I"ve edited my log to show "MYWEBSITE", in actually it shows the proper URL.

**Comment by szaimen** [comment]
Hi, is talk working in general and only the recording doesnt?

**Comment by y4my4my4m** [comment]
@szaimen yes that's correct, Talk is working as expected. Only Talk Recording.
It'll attempt to start recording, then say "recording couldn't start contact your administrator".

I've verified in the Nextcloud Admin > Talk area that the secrets and URls are fine ✅. Attempting to disable SSL verify didn't change anything.

**Comment by y4my4my4m** [comment]
@szaimen 
There are no logs displayed from `nextcloud-aio-talk` when the recording is requested or when it fails to start. The only logs I can retrieve are from `nextcloud-aio-talk-recording`.

However just in case, here are the talk container's logs from the moment the call begins:


```
mcu_janus.go:729: Attached video as publisher 7692915895315011 to plugin janus.plugin.videoroom in session 5248142806922150
mcu_janus.go:767: Created room 6363277375873488 {janus.plugin.videoroom map[permanent:false room:6363277375873488 videoroom:created]}
mcu_janus.go:825: Publisher ZAYwq_IQAjPLlu-pURaSbRpDoETzJ7IwDtO9A0mSmYN8PT1ReUhFa2Ixc0lPSHBZNGY2UmcyYU1TQmFFcjAwcFc5d2hHakhqNExVVmFoV0pVVkZNU2RWZXZrX01XTEV4SzQ3VTNqenRsOXcwbWFjYlc3eXBOd3dlZFhGbDdOWDVUemJQOFRpY01uRU9ya2JLd084QXMzLUtudHg5aHExVUtlRW9VYnRnNXBFUnM5WWFoOUY4Z1BDWjY4T3Ywei1nWFlEeXEtSlhCbzdXcDd2WEZ8NDUzNzAyMzk2MQ== is using handle 7692915895315011
clientsession.go:890: Publishing video as 37 for session ZAYwq_IQAjPLlu-pURaSbRpDoETzJ7IwDtO9A0mSmYN8PT1ReUhFa2Ixc0lPSHBZNGY2UmcyYU1TQmFFcjAwcFc5d2hHakhqNExVVmFoV0pVVkZNU2RWZXZrX01XTEV4SzQ3VTNqenRsOXcwbWFjYlc3eXBOd3dlZFhGbDdOWDVUemJQOFRpY01uRU9ya2JLd084QXMzLUtudHg5aHExVUtlRW9VYnRnNXBFUnM5WWFoOUY4Z1BDWjY4T3Ywei1nWFlEeXEtSlhCbzdXcDd2WEZ8NDUzNzAyMzk2MQ==
room.go:656: Session ZAYwq_IQAjPLlu-pURaSbRpDoETzJ7IwDtO9A0mSmYN8PT1ReUhFa2Ixc0lPSHBZNGY2UmcyYU1TQmFFcjAwcFc5d2hHakhqNExVVmFoV0pVVkZNU2RWZXZrX01XTEV4SzQ3VTNqenRsOXcwbWFjYlc3eXBOd3dlZFhGbDdOWDVUemJQOFRpY01uRU9ya2JLd084QXMzLUtudHg5aHExVUtlRW9VYnRnNXBFUnM5WWFoOUY4Z1BDWjY4T3Ywei1nWFlEeXEtSlhCbzdXcDd2WEZ8NDUzNzAyMzk2MQ== joined call e84eo65e
mcu_janus.go:864: Publisher 7692915895315011 received connected
mcu_janus.go:729: Attached video as publisher 4000752476680495 to plugin janus.plugin.videoroom in session 5248142806922150
mcu_janus.go:767: Created room 4096850327570173 {janus.plugin.videoroom map[permanent:false room:4096850327570173 videoroom:created]}
mcu_janus.go:825: Publisher zcsio_1EfDMbwtWWnBrN0X7LBnipmm1NrlmZO-D8I7J8PT13b0tkLVE0bk1pR1hILXVwRElfaVVIUk1Yd3l2NHdkR1dhNERTYkdhdEJGVjVWTjZJYU1QSTRNNmJoOGdvY19EUi1iVmltWjlyM1RVRUlmSUFsQnpNcVhTSXZCQ0lFY3NSdUdjclhSOFpZM3ZRcVhkVC1QcThrN1ZSbjlqakV3X1BqWmtzaUJYdUNzbDM0MjJKZWI0VERUQ1g3STRWMEpmbW1LR1ctajNROUUxWVF8NDM0NzAyMzk2MQ== is using handle 4000752476680495
clientsession.go:890: Publishing video as 38 for session zcsio_1EfDMbwtWWnBrN0X7LBnipmm1NrlmZO-D8I7J8PT13b0tkLVE0bk1pR1hILXVwRElfaVVIUk1Yd3l2NHdkR1dhNERTYkdhdEJGVjVWTjZJYU1QSTRNNmJoOGdvY19EUi1iVmltWjlyM1RVRUlmSUFsQnpNcVhTSXZCQ0lFY3NSdUdjclhSOFpZM3ZRcVhkVC1QcThrN1ZSbjlqakV3X1BqWmtzaUJYdUNzbDM0MjJKZWI0VERUQ1g3STRWMEpmbW1LR1ctajNROUUxWVF8NDM0NzAyMzk2MQ==
room.go:656: Session zcsio_1EfDMbwtWWnBrN0X7LBnipmm1NrlmZO-D8I7J8PT13b0tkLVE0bk1pR1hILXVwRElfaVVIUk1Yd3l2NHdkR1dhNERTYkdhdEJGVjVWTjZJYU1QSTRNNmJoOGdvY19EUi1iVmltWjlyM1RVRUlmSUFsQnpNcVhTSXZCQ0lFY3NSdUdjclhSOFpZM3ZRcVhkVC1QcThrN1ZSbjlqakV3X1BqWmtzaUJYdUNzbDM0MjJKZWI0VERUQ1g3STRWMEpmbW1LR1ctajNROUUxWVF8NDM0NzAyMzk2MQ== joined call e84eo65e
mcu_janus.go:1024: Attached subscriber to room 4096850327570173 of publisher zcsio_1EfDMbwtWWnBrN0X7LBnipmm1NrlmZO-D8I7J8PT13b0tkLVE0bk1pR1hILXVwRElfaVVIUk1Yd3l2NHdkR1dhNERTYkdhdEJGVjVWTjZJYU1QSTRNNmJoOGdvY19EUi1iVmltWjlyM1RVRUlmSUFsQnpNcVhTSXZCQ0lFY3NSdUdjclhSOFpZM3ZRcVhkVC1QcThrN1ZSbjlqakV3X1BqWmtzaUJYdUNzbDM0MjJKZWI0VERUQ1g3STRWMEpmbW1LR1ctajNROUUxWVF8NDM0NzAyMzk2MQ== in plugin janus.plugin.videoroom in session 5248142806922150 as 4605025568223479
clientsession.go:967: Subscribing video from zcsio_1EfDMbwtWWnBrN0X7LBnipmm1NrlmZO-D8I7J8PT13b0tkLVE0bk1pR1hILXVwRElfaVVIUk1Yd3l2NHdkR1dhNERTYkdhdEJGVjVWTjZJYU1QSTRNNmJoOGdvY19EUi1iVmltWjlyM1RVRUlmSUFsQnpNcVhTSXZCQ0lFY3NSdUdjclhSOFpZM3ZRcVhkVC1QcThrN1ZSbjlqakV3X1BqWmtzaUJYdUNzbDM0MjJKZWI0VERUQ1g3STRWMEpmbW1LR1ctajNROUUxWVF8NDM0NzAyMzk2MQ== as 39 in session ZAYwq_IQAjPLlu-pURaSbRpDoETzJ7IwDtO9A0mSmYN8PT1ReUhFa2Ixc0lPSHBZNGY2UmcyYU1TQmFFcjAwcFc5d2hHakhqNExVVmFoV0pVVkZNU2RWZXZrX01XTEV4SzQ3VTNqenRsOXcwbWFjYlc3eXBOd3dlZFhGbDdOWDVUemJQOFRpY01uRU9ya2JLd084QXMzLUtudHg5aHExVUtlRW9VYnRnNXBFUnM5WWFoOUY4Z1BDWjY4T3Ywei1nWFlEeXEtSlhCbzdXcDd2WEZ8NDUzNzAyMzk2MQ==
mcu_janus.go:1024: Attached subscriber to room 6363277375873488 of publisher ZAYwq_IQAjPLlu-pURaSbRpDoETzJ7IwDtO9A0mSmYN8PT1ReUhFa2Ixc0lPSHBZNGY2UmcyYU1TQmFFcjAwcFc5d2hHakhqNExVVmFoV0pVVkZNU2RWZXZrX01XTEV4SzQ3VTNqenRsOXcwbWFjYlc3eXBOd3dlZFhGbDdOWDVUemJQOFRpY01uRU9ya2JLd084QXMzLUtudHg5aHExVUtlRW9VYnRnNXBFUnM5WWFoOUY4Z1BDWjY4T3Ywei1nWFlEeXEtSlhCbzdXcDd2WEZ8NDUzNzAyMzk2MQ== in plugin janus.plugin.videoroom in session 5248142806922150 as 5554803708056149
clientsession.go:967: Subscribing video from ZAYwq_IQAjPLlu-pURaSbRpDoETzJ7IwDtO9A0mSmYN8PT1ReUhFa2Ixc0lPSHBZNGY2UmcyYU1TQmFFcjAwcFc5d2hHakhqNExVVmFoV0pVVkZNU2RWZXZrX01XTEV4SzQ3VTNqenRsOXcwbWFjYlc3eXBOd3dlZFhGbDdOWDVUemJQOFRpY01uRU9ya2JLd084QXMzLUtudHg5aHExVUtlRW9VYnRnNXBFUnM5WWFoOUY4Z1BDWjY4T3Ywei1nWFlEeXEtSlhCbzdXcDd2WEZ8NDUzNzAyMzk2MQ== as 40 in session zcsio_1EfDMbwtWWnBrN0X7LBnipmm1NrlmZO-D8I7J8PT13b0tkLVE0bk1pR1hILXVwRElfaVVIUk1Yd3l2NHdkR1dhNERTYkdhdEJGVjVWTjZJYU1QSTRNNmJoOGdvY19EUi1iVmltWjlyM1RVRUlmSUFsQnpNcVhTSXZCQ0lFY3NSdUdjclhSOFpZM3ZRcVhkVC1QcThrN1ZSbjlqakV3X1BqWmtzaUJYdUNzbDM0MjJKZWI0VERUQ1g3STRWMEpmbW1LR1ctajNROUUxWVF8NDM0NzAyMzk2MQ==
mcu_janus.go:558: Started listener &{{janus.plugin.videoroom map[room:4096850327570173 started:ok videoroom:event]} map[] 5248142806922150 4605025568223479}
mcu_janus.go:558: Started listener &{{janus.plugin.videoroom map[room:6363277375873488 started:ok videoroom:event]} map[] 5248142806922150 5554803708056149}
mcu_janus.go:864: Publisher 4000752476680495 received connected
mcu_janus.go:1107: Subscriber 5554803708056149 received connected
mcu_janus.go:1107: Subscriber 4605025568223479 received connected
client.go:282: Client ZAYwq_IQAjPLlu-pURaSbRpDoETzJ7IwDtO9A0mSmYN8PT1ReUhFa2Ixc0lPSHBZNGY2UmcyYU1TQmFFcjAwcFc5d2hHakhqNExVVmFoV0pVVkZNU2RWZXZrX01XTEV4SzQ3VTNqenRsOXcwbWFjYlc3eXBOd3dlZFhGbDdOWDVUemJQOFRpY01uRU9ya2JLd084QXMzLUtudHg5aHExVUtlRW9VYnRnNXBFUnM5WWFoOUY4Z1BDWjY4T3Ywei1nWFlEeXEtSlhCbzdXcDd2WEZ8NDUzNzAyMzk2MQ== has RTT of 173 ms (173.332412ms)
client.go:282: Client zcsio_1EfDMbwtWWnBrN0X7LBnipmm1NrlmZO-D8I7J8PT13b0tkLVE0bk1pR1hILXVwRElfaVVIUk1Yd3l2NHdkR1dhNERTYkdhdEJGVjVWTjZJYU1QSTRNNmJoOGdvY19EUi1iVmltWjlyM1RVRUlmSUFsQnpNcVhTSXZCQ0lFY3NSdUdjclhSOFpZM3ZRcVhkVC1QcThrN1ZSbjlqakV3X1BqWmtzaUJYdUNzbDM0MjJKZWI0VERUQ1g3STRWMEpmbW1LR1ctajNROUUxWVF8NDM0NzAyMzk2MQ== has RTT of 250 ms (250.405277ms)
```

**Comment by szaimen** [comment]
Hm...

**Comment by szaimen** [comment]
This looks like the underlying issue:

> WebDriver session does not exist, or is not active

**Comment by szaimen** [comment]
I found this thread: https://stackoverflow.com/questions/56483403/selenium-common-exceptions-webdriverexception-message-invalid-session-id-using

**Comment by szaimen** [comment]
How much ram and how many cpus does your server has btw?

**Comment by y4my4my4m** [comment]
@szaimen 

> I found this thread: https://stackoverflow.com/questions/56483403/selenium-common-exceptions-webdriverexception-message-invalid-session-id-using

I did the auto install from AIO dashboard. However I am using an nginx reverse proxy (from the Readme).
Are there specific requirements that I need to add to the reverse proxy for talk-recording?

> How much ram and how many vcpus does your server has btw?


As per Nextcloud's system info:

```
CPU: Intel(R) Xeon(R) CPU D-1521 @ 2.40GHz (4 cores)
Memory: 4.84 GB
```

Not sure why it shows 4GB because I actually have 6GB but i suppose docker and the OS itself is eating a bunch of it? 
4 vCPUs

**Comment by szaimen** [comment]
Thanks! Which optional addons do you have enabled in the aio interface?

**Comment by y4my4my4m** [comment]
@szaimen 
![image](https://github.com/nextcloud/all-in-one/assets/8145020/156716a4-1d7b-49d7-a8eb-a8ce2f8005de)

I barely have anything on it by the way, this is a fresh install.

**Comment by szaimen** [comment]
Hm... that should usually work fine. Can you monitor the ressource usage of the server when you are attempting to record a call? Can you for that e.g. use htop on the server and post a screenshot when attempting to start the recording?

**Comment by szaimen** [comment]
Also can you please post the output of the following command here after the recording fails to start?
`sudo docker exec nextcloud-aio-talk-recording cat geckodriver.log`

**Comment by szaimen** [comment]
Moving to discussions as I cannot reproduce this and without the above information it is not possible to further debug this.
