### ISSUE TITLE
FullTextSearch fails to start: Plugin [00Tree.html] is missing a descriptor properties file.

### ISSUE THREAD

**Issue by rlew-is** [nextcloud/all-in-one#3331]
### Steps to reproduce
1. Starting containers from the AIO interface causes fulltextsearch to enter a restart loop.

### Expected behavior 
Containers boot as usual and all is well.

### Actual behavior 
Containers start until fulltextsearch encounters the error, as nextcloud itself is waiting on it it too fails to start.

### Host OS 
Ubuntu 22.04.3 LTS
Docker 24.0.5

#### Nextcloud AIO version 
v7.0.0

#### Current channel 
latest

#### Other valuable info 
I have restored backups from a last known working time.
I have tried to "start and update" containers.
I have removed the fulltextsearch volume.
I have removed all containers and restarted.
The error still persists, I'm unsure if this is related to a recent update?
This is the relevant error from the fulltextsearch container log:

`fatal exception while booting Elasticsearch | @timestamp=2023-09-11T19:56:26.389Z log.level=ERROR ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=main log.logger=org.elasticsearch.bootstrap.Elasticsearch elasticsearch.node.name=c82fc0115480 elasticsearch.cluster.name=nextcloud-aio error.type=java.lang.IllegalStateException error.message=Plugin [00Tree.html] is missing a descriptor properties file. error.stack_trace=java.lang.IllegalStateException: Plugin [00Tree.html] is missing a descriptor properties file.
	at org.elasticsearch.server@8.8.1/org.elasticsearch.plugins.PluginDescriptor.readFromProperties(PluginDescriptor.java:199)
	at org.elasticsearch.server@8.8.1/org.elasticsearch.plugins.PluginsUtils.readPluginBundle(PluginsUtils.java:185)
	at org.elasticsearch.server@8.8.1/org.elasticsearch.plugins.PluginsUtils.findBundles(PluginsUtils.java:166)
	at org.elasticsearch.server@8.8.1/org.elasticsearch.plugins.PluginsUtils.getPluginBundles(PluginsUtils.java:148)
	at org.elasticsearch.server@8.8.1/org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:170)
	at org.elasticsearch.server@8.8.1/org.elasticsearch.plugins.PluginsService.lambda$getPluginsServiceCtor$17(PluginsService.java:680)
	at org.elasticsearch.server@8.8.1/org.elasticsearch.node.Node.<init>(Node.java:420)
	at org.elasticsearch.server@8.8.1/org.elasticsearch.node.Node.<init>(Node.java:327)
	at org.elasticsearch.server@8.8.1/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:216)
	at org.elasticsearch.server@8.8.1/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:216)
	at org.elasticsearch.server@8.8.1/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)`

**Comment by rlew-is** [comment]
So this is a self caused issue. In diagnosing a previous issue where my docker/overlay2 directory was so big I entered the command
`tree -d -R -L 1 overlay2/`
The -R argument saved a "00Tree.html" file in nearly every directory. Some of those belong to fulltextsearch and I assume caused the error.
Removing the files causes everything to boot up normally. I guess it was my turn today to make a stupid mistake.
