### ISSUE TITLE
Slim error appears related to "nextcloud-aio-domaincheck" when that was skipped for reverse proxy

### ISSUE THREAD

**Issue by ShapeShifter499** [nextcloud/all-in-one#3599]
Moved to issues since it appears to be a bug/issue rather than a misconfiguration from what I can tell.

### Discussed in https://github.com/nextcloud/all-in-one/discussions/3592

<div type='discussions-op-text'>

<sup>Originally posted by **ShapeShifter499** October 23, 2023</sup>
Hi, I'm seeing the following 'slim error' and I'm entirely sure what it's from. Does anyone know?

Running Nextcloud AIO v7.5.0 BETA generated after this https://github.com/nextcloud/all-in-one/issues/3566
Nextcloud = 27.1.2

System Specs
Operating System: Linux 6.1.55-1-MANJARO x86_64
CPU: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 cores)
Memory: 16GB

```
Initial startup of Nextcloud All-in-One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080

If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443
[Mon Oct 23 14:50:17.617192 2023] [mpm_event:notice] [pid 128:tid 140437168409416] AH00489: Apache/2.4.58 (Unix) OpenSSL/3.1.3 configured -- resuming normal operations
[Mon Oct 23 14:50:17.617600 2023] [core:notice] [pid 128:tid 140437168409416] AH00094: Command line: 'httpd -D FOREGROUND'
{"level":"info","ts":1698072617.622524,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
[23-Oct-2023 14:50:17] NOTICE: fpm is running, pid 134
[23-Oct-2023 14:50:17] NOTICE: ready to handle connections
NOTICE: PHP message: 404 Not Found
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 76
Trace: #0 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(56): Slim\Middleware\RoutingMiddleware->performRouting(Object(GuzzleHttp\Psr7\ServerRequest))
#1 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(476): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#2 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#3 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#4 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#5 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#7 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#8 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#9 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#10 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#11 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#12 /var/www/docker-aio/php/public/index.php(182): Slim\App->run()
#13 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
```</div>

**Comment by ShapeShifter499** [comment]
I'm seeing references to "nextcloud-aio-domaincheck" after a reboot. Which makes sense, I skipped it with `--env SKIP_DOMAIN_VALIDATION=true` since my install is behind a reverse proxy, haproxy. Isn't this a error that can be safely ignored then? Why is it still trying to verify for "nextcloud-aio-domaincheck" in this case?

```
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 959

.+++++++++++++++++++++++++++++++++++++++++++++*.+...........................+......+.+......+..+.+++++++++++++++++++++++++++++++++++++++++++++*.....+..........+.....................+..................+..+....+...+.....+..............................+.......+.....+.+........+....+..+.........+.+...+...............+...+..............+...+.+..+...+..........+...........+...+............................+.....+....+.....+.........+....+.....+.+..............+.............+........+....+...........+................+.....+...+..................+.........+....+...............+......+...+...+..+......+.+.....+................+..+.+..+.........+.+.....+.............+..+.......+...+..+...+............+.......+...+...+.....+...+.+........+.+......+.....+.........+.........+..........+..+....+..............+.....................+.+...+........+....+.....................+...+............+..................+..............+...+....+...........+...+.........+.+............+...+......+.....+...+.............+..+...+....+.....+.+...+............+..............+......+.............+......+.........+.....+......+...+..........+.....+...+...+.+...........+...............+....+...........+..........+..+..........+...+.......................+.........+..........+....................+.......+.......................+......+.+.........+......+...........+.......+...+..................+.........+..+....+..+.......+..+....+.................+...+...............+.+........+............+.+.....+....+.......................+.+..+.............+++++
...+...+............+++++++++++++++++++++++++++++++++++++++++++++*...+..+...+.+...+......+..+++++++++++++++++++++++++++++++++++++++++++++*....+...........+.........+...+.......+............+......+.....+.........+.............+.................+...+.+...............+..+...+..........+..+...+.......+...........................+.................+......+.......+...+...........................+.....................+.....+.+.....+.+.....+....+......+.........+.....+...................+..+.......+..+...+...+............+.+..+...+.........+.............+.....+....+.....+.+..+..........+.................+....+......+...............+...+......+..+.............+............+.................+......+....+......+............+..............+......+...+.+...+.................+.+...............+........+.+........+.......+.........+.....+.........+.+++++
-----
[0;92mInitial startup of Nextcloud All-in-One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080

If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443[0m
[Mon Oct 23 14:50:17.617192 2023] [mpm_event:notice] [pid 128:tid 140437168409416] AH00489: Apache/2.4.58 (Unix) OpenSSL/3.1.3 configured -- resuming normal operations
[Mon Oct 23 14:50:17.617600 2023] [core:notice] [pid 128:tid 140437168409416] AH00094: Command line: 'httpd -D FOREGROUND'
{"level":"info","ts":1698072617.622524,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
[23-Oct-2023 14:50:17] NOTICE: fpm is running, pid 134
[23-Oct-2023 14:50:17] NOTICE: ready to handle connections
NOTICE: PHP message: 404 Not Found
Type: Slim\Exception\HttpNotFoundException

4
Message: Not found.
File: /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 76
Trace: #0 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(56): Slim\Middleware\RoutingMiddleware->performRouting(Object(GuzzleHttp\Psr7\ServerRequest))
#1 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(476): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#2 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#3 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#4 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#5 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#7 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#8 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#9 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#10 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#11 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#12 /var/www/docker-aio/php/public/index.php(182): Slim\App->run()
#13 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
nextcloud-aio-domaincheck
Total reclaimed space: 0B
NOTICE: PHP message: 404 Not Found
Type: Slim\Exception\HttpNotFoundException

4
Message: Not found.
File: /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 76
Trace: #0 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(56): Slim\Middleware\RoutingMiddleware->performRouting(Object(GuzzleHttp\Psr7\ServerRequest))
#1 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(476): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#2 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#3 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#4 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#5 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#7 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#8 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#9 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#10 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#11 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#12 /var/www/docker-aio/php/public/index.php(182): Slim\App->run()
#13 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
```

**Comment by szaimen** [comment]
> NOTICE: PHP message: 404 Not Found
> Type: Slim\Exception\HttpNotFoundException

Hi, these are logged but usually do not introduce any problem. Unfortunatley I did not suceed in not logging 404 issues. So nothing we can fix here afaics.
