### ISSUE TITLE
Weird errors in OnlyOffice

### ISSUE THREAD

**Issue by FlattusBlastus** [nextcloud/all-in-one#3603]
### Steps to reproduce
1. Set OnlyOffice to open PDF by default
2. Perform docker exec --user www-data -it nextcloud-aio-nextcloud php occ preview:generate-all -vvv

### Expected behavior 
No messages; all is well
### Actual behavior 
2023-10-24 01:34:46 2023/10/24 04:18:50 [error] 7874#7874: *3823 upstream timed out (110: Unknown error) while reading response header from upstream, client: 172.18.0.13, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://[::1]:8000/ConvertService.ashx", host: "babfam.us"
2023-10-24 01:34:46 2023/10/24 06:58:28 [error] 7874#7874: *4735 upstream timed out (110: Unknown error) while reading response header from upstream, client: 172.18.0.13, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://127.0.0.1:8000/ConvertService.ashx", host: "babfam.us"
2023-10-24 01:34:46 2023/10/24 07:20:50 [error] 7874#7874: *5091 upstream timed out (110: Unknown error) while reading response header from upstream, client: 172.18.0.13, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://[::1]:8000/ConvertService.ashx", host: "babfam.us"
2023-10-24 01:34:46 2023/10/24 07:45:19 [error] 7874#7874: *5398 upstream timed out (110: Unknown error) while reading response header from upstream, client: 172.18.0.13, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://[::1]:8000/ConvertService.ashx", host: "babfam.us"
2023-10-24 01:34:46 2023/10/24 08:03:49 [error] 7874#7874: *5508 upstream timed out (110: Unknown error) while reading response header from upstream, client: 172.18.0.13, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://127.0.0.1:8000/ConvertService.ashx", host: "babfam.us"
2023-10-24 01:34:46 2023/10/24 08:07:44 [error] 722#722: *1 connect() failed (111: Unknown error) while connecting to upstream, client: 172.18.0.13, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://[::1]:8000/ConvertService.ashx", host: "babfam.us"
2023-10-24 01:34:46 2023/10/24 08:07:44 [error] 722#722: *1 connect() failed (111: Unknown error) while connecting to upstream, client: 172.18.0.13, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://127.0.0.1:8000/ConvertService.ashx", host: "babfam.us"
2023-10-24 01:34:46 2023/10/24 08:07:56 [error] 722#722: *1 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.13, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://[::1]:8000/ConvertService.ashx", host: "babfam.us"
2023-10-24 01:34:46 2023/10/24 08:14:18 [error] 718#718: *1 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.13, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://[::1]:8000/ConvertService.ashx", host: "babfam.us"
2023-10-24 01:34:47 
2023-10-24 01:34:47 ==> /var/log/onlyoffice/documentserver/converter/out.log <==
2023-10-24 01:34:47 [2023-10-24T08:34:47.367] [ERROR] [localhost] [conv_1610405146_jpeg] [userId] nodeJS - error downloadFile:url=https://babfam.us/index.php/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJkb3dubG9hZCIsImZpbGVJZCI6NDE1Mjd9.eyZBonbG4BH7qEdddUzPRPfN4sjDoNvZkKvZEybZazY;attempt=2;code:null;connect:null Error: Error response: statusCode:400; headers:{"server":"openresty","date":"Tue, 24 Oct 2023 08:34:47 GMT","content-type":"application/json; charset=utf-8","content-length":"29","connection":"close","cache-control":"no-cache, no-store, must-revalidate","content-security-policy":"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'","expires":"Thu, 19 Nov 1981 08:52:00 GMT","feature-policy":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'","pragma":"no-cache","referrer-policy":"no-referrer","set-cookie":["oc_sessionPassphrase=XvWUi3gvo4G8S%2B0PCI3hKLqrgMBQyLc1Dy2QiOvpT%2FMViSOr6y1HbdEM2RJ53vPID2WJSIiIxVZt%2FNBwZTHOgpbimHePtzzkgA8EgqpRk00rJaHtMZ4FN7H2umwZJ93i; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict","oc4dw3y81gxs=7066c2216c44683e575fca77604721fa; path=/; secure; HttpOnly; SameSite=Lax"],"strict-transport-security":"max-age=31536000;","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-powered-by":"PHP/8.1.24","x-request-id":"NhMqXA1iHbEO8iLrDkao","x-robots-tag":"noindex, nofollow","x-xss-protection":"1; mode=block","access-control-allow-origin":"*","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, PUT, DELETE, OPTIONS","access-control-allow-headers":"Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With","access-control-expose-headers":"Authorization"};
2023-10-24 01:34:47     at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
2023-10-24 01:34:47     at Request.emit (events.js:400:28)
2023-10-24 01:34:47     at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1066:10)
2023-10-24 01:34:47     at ClientRequest.emit (events.js:400:28)
2023-10-24 01:34:47     at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
2023-10-24 01:34:47     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
2023-10-24 01:34:47     at TLSSocket.socketOnData (_http_client.js:515:22)
2023-10-24 01:34:47     at TLSSocket.emit (events.js:400:28)
2023-10-24 01:34:47     at addChunk (internal/streams/readable.js:293:12)
2023-10-24 01:34:47     at readableAddChunk (internal/streams/readable.js:267:9)
2023-10-24 01:34:47     at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
2023-10-24 01:34:47     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

### Host OS 
Windows 11 - DDfW

#### Nextcloud AIO version 
27.1.2
#### Current channel 
Develop

**Comment by szaimen** [comment]
Hi, it sounds like this should be reported to https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues
