### ISSUE TITLE
Problem with starting nextcloud-aio-nextcloud when nextcloud-dlna is enabled

### ISSUE THREAD

**Issue by thanek** [nextcloud/all-in-one#3671]
### Steps to reproduce
1. Run AIO without any community container enabled
2. Click `Stop containers` and then stop the mastercontainer
3. Start the mastercontainer with env variable `--env AIO_COMMUNITY_CONTAINERS="dlna"`
4. Click `Start and update containers`

### Expected behavior 
All the containers are up 

### Actual behavior 
Only the Database and DLNA container are up

### Host OS 
Linux Mint

#### Nextcloud AIO version 
7.6.1

#### Current channel 
beta

#### Other valuable info 

Mastercontainer log:

```Trying to fix docker.sock permissions internally...
Creating docker group internally with id 138
Initial startup of Nextcloud All-in-One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080

If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443
[Fri Nov 03 16:17:15.776353 2023] [mpm_event:notice] [pid 116:tid 140443719842632] AH00489: Apache/2.4.58 (Unix) OpenSSL/3.1.4 configured -- resuming normal operations
[Fri Nov 03 16:17:15.776742 2023] [core:notice] [pid 116:tid 140443719842632] AH00094: Command line: 'httpd -D FOREGROUND'
{"level":"info","ts":1699028235.7926612,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
[03-Nov-2023 16:17:15] NOTICE: fpm is running, pid 122
[03-Nov-2023 16:17:15] NOTICE: ready to handle connections
NOTICE: PHP message: Slim Application Error
Type: GuzzleHttp\Exception\ClientException
Code: 409
Message: Client error: `DELETE http://localhost/v1.41/containers/nextcloud-aio-database?v=true` resulted in a `409 Conflict` response:
{&quot;message&quot;:&quot;You cannot remove a running container 6a69b4ea08ec981ed93b272920978ccc1b20ac6a8c9bd712da4debbcaf833e4b. Stop (truncated...)
File: /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php
Line: 113
Trace: #0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/ClientTrait.php(129): GuzzleHttp\Client->request('DELETE', 'http://localhos...', Array)
#11 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(157): GuzzleHttp\Client->delete('http://localhos...')
#12 /var/www/docker-aio/php/src/Controller/DockerController.php(42): AIO\Docker\DockerActionManager->DeleteContainer(Object(AIO\Container\Container))
#13 /var/www/docker-aio/php/src/Controller/DockerController.php(33): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-d...', true)
#14 /var/www/docker-aio/php/src/Controller/DockerController.php(33): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-n...', true)
#15 /var/www/docker-aio/php/src/Controller/DockerController.php(193): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-a...', true)
#16 /var/www/docker-aio/php/src/Controller/DockerController.php(173): AIO\Controller\DockerController->startTopContainer(true)
#17 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): AIO\Controller\DockerController->StartContainer(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#18 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#19 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#20 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#21 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#22 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
#23 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(476): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#24 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#25 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#26 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#27 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#28 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#29 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#30 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#31 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#32 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#33 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#34 /var/www/docker-aio/php/public/index.php(182): Slim\App->run()
#35 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.


```

I'm guessing it's connected to with the `depends_on` entry in the DLNA containers config.

**Comment by szaimen** [comment]
> 2\. Click `Stop containers` and then stop the mastercontainer

Did you wait until all containers were stopped before stopping the mastercontainer and recreating it? Also did you remoce any data in between?

**Comment by thanek** [comment]
No, I did not. This is a fresh installation and its reproducable on my machine. I am experimenting with removing the `depends_on` part from `dlna.json` but then the nextcloud-dlna containers gets up too early and doesn't have info about the AIO_DB_HOST.

**Comment by szaimen** [comment]
> No, I did not. This is a fresh installation and its reproducable on my machine. I am now experimenting with removing the `depends_on` part from `dlna.json` but then the nextcloud-dlna containers gets up too early and doesn't have info about the AIO_DB_HOST.

All right. Will think about a fix to this then.

**Comment by thanek** [comment]
@szaimen do you think that the fix should be in the AIO or nextcloud-dlna part?

**Comment by szaimen** [comment]
> @szaimen do you think that the fix should be in the AIO or nextcloud-dlna part?

In AIO

**Comment by szaimen** [comment]
We should check if a container that we want remove is still running and then skip any further steps

**Comment by thanek** [comment]
OK, thanks, that makes sense.

**Comment by szaimen** [comment]
Fix is in https://github.com/nextcloud/all-in-one/pull/3682. Reviews are welcome!
