### ISSUE TITLE
Installer broken

### ISSUE THREAD

**Issue by FlattusBlastus** [nextcloud/all-in-one#3862]
### Steps to reproduce
1. Fresh install on latest WSL and DDfW
2. Docker compose:
version: '3.8'
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
networks:
  nextcloud-aio:
    name: nextcloud-aio
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd12:3456:789a:2::/64 # IPv6 subnet to use
services:
  nextcloud:
    image: nextcloud/all-in-one:develop
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - //var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_MOUNT=/mnt/d #This will use your D drive for the external storage. Leave it off if you dont have another drive.
      - SKIP_DOMAIN_VALIDATION=true
      - NEXTCLOUD_MEMORY_LIMIT=2048M #Running on less is not recommended.
      - NEXTCLOUD_ADDITIONAL_APKS=imagemagick ocrmypdf tesseract-ocr-data-deu
      - NEXTCLOUD_STARTUP_APPS=twofactor_totp user_usage_report quota_warning deck files_scripts calendar_resource_management gestion files_lock memories notes files_zip calendar cloud_py_api group_default_quota notify_push camerarawpreviews files_accesscontrol richdocuments recognize tasks user_migration files_notify_redis groupfolders groupquota analytics previewgenerator workflow_script files_automatedtagging side_menu contacts mediadc externalportal integration_youtube files_downloadactivity approval forms sharerenamer integration_onedrive files_antivirus files_confidential mail collectives phonetrack files_fulltextsearch music sociallogin appointments cospend fulltextsearch_elasticsearch maps google_synchronization keeweb tables event_update_notification flow_notifications files_photospheres announcementcenter fulltextsearch bookmarks unsplash files_bpm registration polls files_fulltextsearch_tesseract metadata workflow_pdf_converter workflow_ocr group_everyone login_notes external
      - AUTOMATIC_UPDATES=1
      - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick
    networks:
      - nextcloud-aio

### Expected behavior 
Happyness and rainbows
### Actual behavior 
BOOM - Error in MasterContainer. See Logs.

### Host OS 
Windows 11 23H2

#### Current channel 
Develop, beta, latest
#### Other valuable info 
2023-12-02 19:18:49 WARNING: No blkio throttle.read_bps_device support
2023-12-02 19:18:49 WARNING: No blkio throttle.write_bps_device support
2023-12-02 19:18:49 WARNING: No blkio throttle.read_iops_device support
2023-12-02 19:18:49 WARNING: No blkio throttle.write_iops_device support
2023-12-02 19:18:49 WARNING: daemon is not using the default seccomp profile
2023-12-02 19:18:51 ..+++++++++++++++++++++++++++++++++++++++++++++*..+.......+...........+.+...+...+..+......+.......+.........+........+......+.+.....+......+...+......+.+............+++++++++++++++++++++++++++++++++++++++++++++*........+............+...+......+.....+.+...............+...........+..........+..+..........+...+.....+.............+.............................+.+............+..+......+.......+.....+.......+..+.+.....+..............................+....+.....+......+...+.........+.............+..+......+.......+.........+.....+.........+....+......+.....+....+...+...+..+....+........+..........+............+.....+....+...........+...+...............+..................+.......+.....+.....................+..........+.........+...+..+.+......+..............................+.....+....+.....+..........+......+...+..................+.....+.......+.....+......+.+....................+......+.......+......+...............+......+........+.............+.....+....+......+..+............+...+.................................+.......+...+..............+...+...+...+....+...........+.......+..+............+..........+...+........+.............+..+............+................+..+....+...+............+..............+............+.......+........+...+....+..+.+...............+..+............+.............+...+........+.........+............+.....................+..........+.....+.......+.....................+.....+.+...+...+...+..+...+......+.+...+..............+.............+........+.......+.................+...+............+.+......+...............+.....+.........+.......+.......................+.+.........+.........+..+..........+.....+....+...............+.....+....+..+...+................+.........+..+.+............+........+.......+..+.+.........+.....+...+...+....+...+.....+.+..+...+.......+........+.......+...+......+.............................+....+..+...................+...............+.........+..+...+.......+......+.....+...+.......+........+..........+.....+....+...............+............+...+........+..........................................+...+....+.....+.........+....+............+...........+.......+...........+.+.......................+.......+..................+..+......+..........+..+.+......+.........+.................+....+.....+.+..............+...+.+.....+......+.+.....+.......+........+.......+.....+..........+........+...+.+...........+.......+...+..............+....+......+..............+.+.....+.+...............+.....+.............+..............+.+....................+.......+.....+.........+...............+....+..+...+......+......+............+......................+.....+...+.....................+.+..............+.+...+...+........+......+......+.......+........+....+........................+.................+...+................+......+........+......+....+...........+...+...+..................+....+..+...............+...+.......+......+..+...+.........+......+.......+.......................+...+....+...+.........+....................+........................+.+...........+.......+..+....+.........+...........+.......+.....+...+.........+.+.....+.+.........+..+...............+......................+.....+.+..+............+...+.............+..+...+......+...+.+...............+..+...+....+...+....................+...+....+...............+............+...........+...+....+...+.................+.+...........+.+.....+..........+.................+................+.....+.........+...+..........+..+......+......+...+.+.........+........+.......+..+.+...+.............................+.+.....+...............................+........+...............+...+.......+..+......+..........+.....+....+...+............+...+...+............+.....................+.....+.........+.......+.....+................+...+...............+.....+.........+............+..................+...+...............+.........+.............+.....+..........+.....+.......+...+...+..+.+.....+.........+.............+..+.+......+...+........+.............+..+.......+........+............+..........+...+.........+...+..+.+..............+...+.+.....+.......+.........+.....+......+......................+.....+.+.....+.........+...+....+........+.............+..+......+.+...+.....+...+..........+..................+...........+...+.+..+............+.+.........+..+....+.....+.+......+...+..+...............+++++
2023-12-02 19:18:51 ....+...........+...+......+.......+...+..+...+.........+++++++++++++++++++++++++++++++++++++++++++++*.+......+.....+.......+......+..+....+...+......+..+.......+...+...+.........+..+...............+.........+.+...+.....+.......+.....+.+...+.........+..+......+....+.....+.........+.+...........+....+...+.....+.....................+.+......+.....+...+....+..+.+............+.....+.+........................+...+...+..+...+..........+...........+....+..+....+........+............+.........+.......+++++++++++++++++++++++++++++++++++++++++++++*............+...+..+.......+............+......+...+.....+......+......+...............+...+.....................+..................+.+......+......+...............+..+.+.....+.+...+.......................+.........+...+.......+...+......+..............+.............+........+.........+.+...........+.+..............+....+...........+......+.......+...........+.+...........+...+....+............+...............+..............+.+......+...............+.....+.........+...+......+....+...........+....+..+...+.+............+..+++++
2023-12-02 19:18:51 -----
2023-12-02 19:18:52 [Sun Dec 03 03:18:52.854879 2023] [mpm_event:notice] [pid 138:tid 139838698642248] AH00489: Apache/2.4.58 (Unix) OpenSSL/3.1.4 configured -- resuming normal operations
2023-12-02 19:18:52 [Sun Dec 03 03:18:52.854928 2023] [core:notice] [pid 138:tid 139838698642248] AH00094: Command line: 'httpd -D FOREGROUND'
2023-12-02 19:18:52 [03-Dec-2023 03:18:52] NOTICE: fpm is running, pid 144
2023-12-02 19:18:52 [03-Dec-2023 03:18:52] NOTICE: ready to handle connections
2023-12-02 19:18:52 {"level":"info","ts":1701573532.8733444,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
2023-12-02 19:19:48 NOTICE: PHP message: Slim Application Error
2023-12-02 19:19:48 Type: GuzzleHttp\Exception\ClientException
2023-12-02 19:19:48 Code: 400
2023-12-02 19:19:48 Message: Client error: `POST http://localhost/v1.41/containers/create?name=nextcloud-aio-nextcloud` resulted in a `400 Bad Request` response:
2023-12-02 19:19:48 {&quot;message&quot;:&quot;invalid mount config for type \&quot;bind\&quot;: bind source path does not exist: /mnt/d&quot;}
2023-12-02 19:19:48 File: /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php
2023-12-02 19:19:48 Line: 113
2023-12-02 19:19:48 Trace: #0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
2023-12-02 19:19:48 #1 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
2023-12-02 19:19:48 #2 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
2023-12-02 19:19:48 #3 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
2023-12-02 19:19:48 #4 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
2023-12-02 19:19:48 #5 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
2023-12-02 19:19:48 #6 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
2023-12-02 19:19:48 #7 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
2023-12-02 19:18:49 Trying to fix docker.sock permissions internally...
2023-12-02 19:18:49 Adding internal www-data to group root
2023-12-02 19:18:51 Initial startup of Nextcloud All-in-One complete!
2023-12-02 19:18:51 You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
2023-12-02 19:18:51 E.g. https://internal.ip.of.this.server:8080
2023-12-02 19:18:51 
2023-12-02 19:18:51 If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
2023-12-02 19:18:51 https://your-domain-that-points-to-this-server.tld:8443
2023-12-02 19:19:48 #8 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
2023-12-02 19:19:48 #9 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Promise\Promise->wait()
2023-12-02 19:19:48 #10 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(567): GuzzleHttp\Client->request('POST', 'http://localhos...', Array)
2023-12-02 19:19:48 #11 /var/www/docker-aio/php/src/Controller/DockerController.php(56): AIO\Docker\DockerActionManager->CreateContainer(Object(AIO\Container\Container))
2023-12-02 19:19:48 #12 /var/www/docker-aio/php/src/Controller/DockerController.php(33): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-n...', true)
2023-12-02 19:19:48 #13 /var/www/docker-aio/php/src/Controller/DockerController.php(202): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-a...', true)
2023-12-02 19:19:48 #14 /var/www/docker-aio/php/src/Controller/DockerController.php(182): AIO\Controller\DockerController->startTopContainer(true)
2023-12-02 19:19:48 #15 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): AIO\Controller\DockerController->StartContainer(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
2023-12-02 19:19:48 #16 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
2023-12-02 19:19:48 #17 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2023-12-02 19:19:48 #18 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2023-12-02 19:19:48 #19 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2023-12-02 19:19:48 #20 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
2023-12-02 19:19:48 #21 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(476): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2023-12-02 19:19:48 #22 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
2023-12-02 19:19:48 #23 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2023-12-02 19:19:48 #24 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2023-12-02 19:19:48 #25 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2023-12-02 19:19:48 #26 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2023-12-02 19:19:48 #27 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2023-12-02 19:19:48 #28 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2023-12-02 19:19:48 #29 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2023-12-02 19:19:48 #30 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2023-12-02 19:19:48 #31 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2023-12-02 19:19:48 #32 /var/www/docker-aio/php/public/index.php(185): Slim\App->run()
2023-12-02 19:19:48 #33 {main}
2023-12-02 19:19:48 Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.

**Comment by FlattusBlastus** [comment]
Delete this. /mnt/d is insufficient and needs the whole /mnt syntax. I'm a bit rusty.
