### ISSUE TITLE
After recent container Upgrade, nextcloud-aio-redis won't start anymore

### ISSUE THREAD

**Issue by juplayLP** [nextcloud/all-in-one#4308]
### Steps to reproduce
1. Check Mastercontainer for Upgrades
2. Upgrade containers to latest version
3. Try to start NC

### Expected behavior 
Container upgrades run without Issue, and Nextcloud starts up normally

### Actual behavior 
nextcloud-aio-redis container stuck on "Created" (128), when trying to start it manually, I get `(HTTP code 500) server error - unable to find user redis: no matching entries in passwd file`
Issue remains even on Full reinstall (at least when loading a known good backup)
Issue remains switching from stable to beta or vice versa

### Host OS 
Windows 11 Pro Build 22621.ni_release.220506-1250
Docker Version 25.0.3, build 4debf41
Docker Desktop Version 4.28.0 (139021)

#### Nextcloud AIO version 
v7.13.0-v7.13.1 (beta)
#### Current channel 
stable/latest and beta
#### Other valuable info 
![image](https://github.com/nextcloud/all-in-one/assets/16053084/d46e45c7-01a6-4f60-9913-ea2f2c21f6f6)
Screenshot from Docker Desktop when trying to run redis manually
![image](https://github.com/nextcloud/all-in-one/assets/16053084/1ce05f08-25a0-4e32-b164-b43b6e981e3a)
Screenshot from AIO interface

Error log within nextcloud-aio-mastercontainer after full wipe and reinstall, with backup from previously known good state loaded through borgbackup
```2024-03-03 12:59:20 Trying to fix docker.sock permissions internally...
2024-03-03 12:59:20 Adding internal www-data to group root
2024-03-03 12:59:21 Initial startup of Nextcloud All-in-One complete!
2024-03-03 12:59:21 You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
2024-03-03 12:59:21 E.g. https://internal.ip.of.this.server:8080
2024-03-03 12:59:21 
2024-03-03 12:59:21 If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
2024-03-03 12:59:21 https://your-domain-that-points-to-this-server.tld:8443
2024-03-03 12:59:21 WARNING: No blkio throttle.read_bps_device support
2024-03-03 12:59:21 WARNING: No blkio throttle.write_bps_device support
2024-03-03 12:59:21 WARNING: No blkio throttle.read_iops_device support
2024-03-03 12:59:21 WARNING: No blkio throttle.write_iops_device support
2024-03-03 12:59:21 WARNING: daemon is not using the default seccomp profile
2024-03-03 12:59:22 [Sun Mar 03 11:59:22.648290 2024] [mpm_event:notice] [pid 126:tid 140535106566920] AH00489: Apache/2.4.58 (Unix) OpenSSL/3.1.4 configured -- resuming normal operations
2024-03-03 12:59:22 [Sun Mar 03 11:59:22.648359 2024] [core:notice] [pid 126:tid 140535106566920] AH00094: Command line: 'httpd -D FOREGROUND'
2024-03-03 12:59:22 [03-Mar-2024 11:59:22] NOTICE: fpm is running, pid 132
2024-03-03 12:59:22 [03-Mar-2024 11:59:22] NOTICE: ready to handle connections
2024-03-03 12:59:22 {"level":"info","ts":1709467162.6571765,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
2024-03-03 13:14:49 NOTICE: PHP message: Slim Application Error
2024-03-03 13:14:49 Type: Exception
2024-03-03 13:14:49 Code: 0
2024-03-03 13:14:49 Message: Could not start container nextcloud-aio-redis: Server error: `POST http://localhost/v1.41/containers/nextcloud-aio-redis/start` resulted in a `500 Internal Server Error` response:
2024-03-03 13:14:49 {&quot;message&quot;:&quot;unable to find user redis: no matching entries in passwd file&quot;}
2024-03-03 13:14:49 File: /var/www/docker-aio/php/src/Docker/DockerActionManager.php
2024-03-03 13:14:49 Line: 192
2024-03-03 13:14:49 Trace: #0 /var/www/docker-aio/php/src/Controller/DockerController.php(66): AIO\Docker\DockerActionManager->StartContainer(Object(AIO\Container\Container))
2024-03-03 13:14:49 #1 /var/www/docker-aio/php/src/Controller/DockerController.php(33): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-r...', true)
2024-03-03 13:14:49 #2 /var/www/docker-aio/php/src/Controller/DockerController.php(33): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-n...', true)
2024-03-03 13:14:49 #3 /var/www/docker-aio/php/src/Controller/DockerController.php(211): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-a...', true)
2024-03-03 13:14:49 #4 /var/www/docker-aio/php/src/Controller/DockerController.php(191): AIO\Controller\DockerController->startTopContainer(true)
2024-03-03 13:14:49 #5 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): AIO\Controller\DockerController->StartContainer(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
2024-03-03 13:14:49 #6 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
2024-03-03 13:14:49 #7 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-03-03 13:14:49 #8 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-03-03 13:14:49 #9 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-03-03 13:14:49 #10 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
2024-03-03 13:14:49 #11 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(482): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-03-03 13:14:49 #12 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
2024-03-03 13:14:49 #13 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-03-03 13:14:49 #14 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-03-03 13:14:49 #15 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-03-03 13:14:49 #16 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-03-03 13:14:49 #17 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-03-03 13:14:49 #18 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-03-03 13:14:49 #19 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-03-03 13:14:49 #20 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-03-03 13:14:49 #21 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-03-03 13:14:49 #22 /var/www/docker-aio/php/public/index.php(185): Slim\App->run()
2024-03-03 13:14:49 #23 {main}
2024-03-03 13:14:49 Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.```

**Comment by szaimen** [comment]
Hi, I cannot reproduce this unfortunately. Can you run 
```
sudo docker stop nextcloud-aio-redis
sudo docker rm nextcloud-aio-redis
sudo docker image prune -a
```
And afterwards open the AIO interface and try to start the containers again?
