### ISSUE TITLE
Can't get to admin interface when using a windows SMB share

### ISSUE THREAD

**Issue by csm10495** [nextcloud/all-in-one#4396]
### Steps to reproduce
1. Setup via docker-compose like so:
```
...
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
      - z_drive_nextcloud_data:/mnt/ncdata # Our nextcloud data location
    ports:
      - 8001:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
...

  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
    driver_opts:
      type: cifs
      o: user=<USER>,password=<PASSWORD>,addr=<HOST>,file_mode=0777,dir_mode=0777,nobrl,noperm,uid=1000,gid=1000,vers=2.0,mfsymlinks
      device: //server/<PATH>
```

I've tried removing file_mode and dir_mode. I've tried different combos for the 'o' but no luck.
Note that this is a Windows SMB share. It doesn't support regular Unix permissions, hence normally forcing a file/dir mode of 0777 with noperm. Similarly locking doesn't work right, so we have nobrl.

### Expected behavior 
It should startup and be accessible from port 8080

### Actual behavior 
After startup, navigating to port 8080 gets:

```
Warning: session_start(): Session data file is not created by your uid in /var/www/docker-aio/php/public/index.php on line 46

Warning: session_start(): Failed to read session data: files (path: /mnt/docker-aio-config/session/) in /var/www/docker-aio/php/public/index.php on line 46

Fatal error: Uncaught RuntimeException: Invalid CSRF storage. Use session_start() before instantiating the Guard middleware or provide array storage. in /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php:152 Stack trace: #0 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(128): Slim\Csrf\Guard->setStorage(NULL) #1 /var/www/docker-aio/php/public/index.php(40): Slim\Csrf\Guard->__construct(Object(GuzzleHttp\Psr7\HttpFactory)) #2 [internal function]: {closure}() #3 /var/www/docker-aio/php/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Object(Closure), Array) #4 /var/www/docker-aio/php/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(69): Invoker\Invoker->call(Object(Closure), Array) #5 /var/www/docker-aio/php/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\FactoryResolver->resolve(Object(DI\Definition\FactoryDefinition), Array) #6 /var/www/docker-aio/php/vendor/php-di/php-di/src/Container.php(353): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\FactoryDefinition), Array) #7 /var/www/docker-aio/php/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\FactoryDefinition)) #8 /var/www/docker-aio/php/public/index.php(52): DI\Container->get('Slim\\Csrf\\Guard') #9 {main} thrown in /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php on line 152
```

### Host OS 
Win 10

#### Nextcloud AIO version 
latest from docker

#### Current channel 
latest

#### Other valuable info 

logs from the container:

```
2024-03-17 17:19:35 Trying to fix docker.sock permissions internally...
2024-03-17 17:19:35 Adding internal www-data to group root
2024-03-17 17:19:36 Initial startup of Nextcloud All-in-One complete!
2024-03-17 17:19:36 You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
2024-03-17 17:19:35 WARNING: No blkio throttle.read_bps_device support
2024-03-17 17:19:35 WARNING: No blkio throttle.write_bps_device support
2024-03-17 17:19:35 WARNING: No blkio throttle.read_iops_device support
2024-03-17 17:19:35 WARNING: No blkio throttle.write_iops_device support
2024-03-17 17:19:35 WARNING: daemon is not using the default seccomp profile
2024-03-17 17:19:38 {"level":"info","ts":1710721178.6532981,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
2024-03-17 17:19:38 [Mon Mar 18 00:19:38.654588 2024] [mpm_event:notice] [pid 114:tid 140074880523016] AH00489: Apache/2.4.58 (Unix) OpenSSL/3.1.4 configured -- resuming normal operations
2024-03-17 17:19:38 [Mon Mar 18 00:19:38.654990 2024] [core:notice] [pid 114:tid 140074880523016] AH00094: Command line: 'httpd -D FOREGROUND'
2024-03-17 17:19:38 [18-Mar-2024 00:19:38] NOTICE: fpm is running, pid 119
2024-03-17 17:19:38 [18-Mar-2024 00:19:38] NOTICE: ready to handle connections
2024-03-17 17:19:36 E.g. https://internal.ip.of.this.server:8080
2024-03-17 17:19:36 
2024-03-17 17:19:36 If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
2024-03-17 17:19:36 https://your-domain-that-points-to-this-server.tld:8443
```

**Comment by csm10495** [comment]
If it helps, I also can see that it does make session files in /mnt/docker-aio-config/session (though they are empty):

![image](https://github.com/nextcloud/all-in-one/assets/5749838/58110206-6c32-4ba2-8805-93a68e56b3f9)

**Comment by EpicJosch** [comment]
Windows isn't even supported or is it?

**Comment by EpicJosch** [comment]
Tried to setup a test vm on windows and it gave me an error that said windows is not supported for Nextcloud server
