### ISSUE TITLE
Can't complete setup after login on ODROID.

### ISSUE THREAD

**Issue by charlieamer** [nextcloud/all-in-one#4504]
### Steps to reproduce
I am using [odroid](https://www.hardkernel.com/shop/odroid-n2-with-2gbyte-ram-2/). It is arm64. Docker is not rootless.

1. `docker run --init --sig-proxy=false --name nextcloud-aio-mastercontainer --restart always --publish 8080:8080 --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock:ro --env NEXTCLOUD_DATADIR="/mnt/externalhdd/nextcloud" nextcloud/all-in-one:latest`
2. Open AIO Web. I tried with both `IP:8080` and `domain.com`. I am using proxy with certificates from letsencrypt. I don't think the issue is related to the proxy though.
3. Login (this goes successfully)
4. The error appears after login

### Expected behavior 
Not error

### Actual behavior 
I can't proceed after login. Following error is displayed in main container. `Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD -o br-c7e3bd8d8c2b -j DOCKER: ip (truncated...)`

### Host OS 
Ubuntu 22.04

#### Nextcloud AIO version 
I couldn't get to the interface ... sorry

#### Current channel 
`latest`

#### Other valuable info 
I am new to the project please let me know if I can provide any more useful logs.

Screenshot on frontend:

![image](https://github.com/nextcloud/all-in-one/assets/5943275/111ebd93-90d4-4652-8ff4-1b9f6bc285f7)

Console log:
```
docker run --init --sig-proxy=false --name nextcloud-aio-mastercontainer --restart always --publish 8080:8080 --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock:ro --env NEXTCLOUD_DATADIR="/mnt/externalhdd/nextcloud" nextcloud/all-in-one:latest
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 997
....+.....+...+.......+......+......+++++++++++++++++++++++++++++++++++++++++++++*..+..+....+.....+...+.+......+...+++++++++++++++++++++++++++++++++++++++++++++*......+..........+...+.....................+.....+..........+......+...+..+...+.......+..+.+.....+.+........+......+.+...........+....+...+......+...........+...+..........+...............+.....+..............................+...+...+...................+...+..............+.............+..+...+......+............+....+.....+....+...........+....+..+....+.....+......+...+.+...+..............................+..+...+......+....+...+...+.....+.+.....+....+...........+.............+..+.........+.+..............................+...............+...........+....+.....+..........+......+..+......+.........+..........+..+.............+......+...............+......+........+...+..........+.........+......+.........+.....+.............+........+..........+.....+.............+.....+.+......+..................+.....+..........+.........+...+........+.....................+.+..+...+..................................+...+.....+......+......+......+.......+...+..+..........+...+...+.................+....+........+.............+.........+.....+.+...+.....+.......+...+..+....+...+.....+......+....+..+.............+......+..+.......+..................+..+...............+.......+...........+..................+......+....+.....+........................+.+..+....+......+..+...+....+....................+..........+......+.....+.........................+...+.........+..+.............+...+.....+............+.+............+..............+..........+......+...+...........+....+..............+..........+............+..............+.+........+.+.....+....+.................+..................+.+.................+............+...+..................+.........+...............+............+......+...+...................+...........+.+..................+..+................+..+..........+........+...+..........+.................+....+...+..+...+..........+...+........+.+......+.................+.+......+......+..+......+....+...+.....+.......+..+.+...+...........+...+.+..............+......+.+......+..............+......+.......+..+...+............................+.........+...+++++
.....+.+........+.......+..+.+.....+.......+........+.+.....+....+...........+...+...+.......+..+...+...+..........+++++++++++++++++++++++++++++++++++++++++++++*..+............+.....+...+.+..............+.+......+...+..+.......+...+............+..+...+...+...+....+...+...+.........+..+...+.+.....+.+.....+....+++++++++++++++++++++++++++++++++++++++++++++*..................+.+...+.........+...........+.+......+++++
-----
Initial startup of Nextcloud All-in-One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080
⚠️ Important: do always use an ip-address if you access this port and not a domain as HSTS might block access to it later!

If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443
[Fri Apr 05 20:29:19.312321 2024] [mpm_event:notice] [pid 129:tid 548301585664] AH00489: Apache/2.4.58 (Unix) OpenSSL/3.1.4 configured -- resuming normal operations
[Fri Apr 05 20:29:19.312418 2024] [core:notice] [pid 129:tid 548301585664] AH00094: Command line: 'httpd -D FOREGROUND'
[05-Apr-2024 20:29:19] NOTICE: fpm is running, pid 134
[05-Apr-2024 20:29:19] NOTICE: ready to handle connections
{"level":"info","ts":1712348959.3309436,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
NOTICE: PHP message: Slim Application Error
Type: Exception
Code: 0
Message: Could not create the nextcloud-aio network: Server error: `POST http://localhost/v1.41/networks/create` resulted in a `500 Internal Server Error` response:
{&quot;message&quot;:&quot;Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD -o br-c7e3bd8d8c2b -j DOCKER: ip (truncated...)
File: /var/www/docker-aio/php/src/Docker/DockerActionManager.php
Line: 882
Trace: #0 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(909): AIO\Docker\DockerActionManager->ConnectContainerIdToNetwork('nextcloud-aio-m...', '')
#1 /var/www/docker-aio/php/public/index.php(83): AIO\Docker\DockerActionManager->ConnectMasterContainerToNetwork()
#2 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Closure->{closure}(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#4 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#5 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#6 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#7 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
#8 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(482): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#9 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#10 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#11 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#12 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#13 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#14 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#15 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#16 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#17 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#18 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#19 /var/www/docker-aio/php/public/index.php(185): Slim\App->run()
#20 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
```

**Comment by szaimen** [comment]
Hi, see https://www.google.com/search?q=%22Failed%20to%20program%20FILTER%20chain%3A%22
