### ISSUE TITLE
Ubuntu 24.04.1 LTS  cannot run

### ISSUE THREAD

**Issue by snakwu** [nextcloud/all-in-one#5262]
Ubuntu 24.04.1 LTS

![image](https://github.com/user-attachments/assets/004cb727-f0e3-44fb-84f7-faa297bd2047)

log:
2024-09-14T10:33:12.395737684Z Trying to fix docker.sock permissions internally...
2024-09-14T10:33:12.404361167Z Creating docker group internally with id 117
2024-09-14T10:33:14.301751155Z [0;92mInitial startup of Nextcloud All-in-One complete!
2024-09-14T10:33:14.301797857Z You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
2024-09-14T10:33:14.301804057Z E.g. https://internal.ip.of.this.server:8080
2024-09-14T10:33:14.301809357Z ⚠️ Important: do always use an ip-address if you access this port and not a domain as HSTS might block access to it later!
2024-09-14T10:33:14.301814958Z 
2024-09-14T10:33:14.301819858Z If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
2024-09-14T10:33:14.301824958Z https://your-domain-that-points-to-this-server.tld:8443[0m
2024-09-14T10:33:15.592509526Z {"level":"info","ts":1726309995.5921538,"msg":"using config from file","file":"/Caddyfile"}
2024-09-14T10:33:15.593567973Z {"level":"info","ts":1726309995.593341,"msg":"adapted config to JSON","adapter":"caddyfile"}
2024-09-14T10:33:15.599460134Z [Sat Sep 14 10:33:15.599226 2024] [mpm_event:notice] [pid 186:tid 186] AH00489: Apache/2.4.62 (Unix) OpenSSL/3.3.2 configured -- resuming normal operations
2024-09-14T10:33:15.599471935Z [Sat Sep 14 10:33:15.599269 2024] [core:notice] [pid 186:tid 186] AH00094: Command line: 'httpd -D FOREGROUND'
2024-09-14T10:33:15.626648441Z [14-Sep-2024 10:33:15] NOTICE: fpm is running, pid 191
2024-09-14T10:33:15.626660441Z [14-Sep-2024 10:33:15] NOTICE: ready to handle connections
2024-09-14T10:35:42.954019463Z NOTICE: PHP message: Slim Application Error
2024-09-14T10:35:42.954387279Z Type: Exception
2024-09-14T10:35:42.954411280Z Code: 0
2024-09-14T10:35:42.954424481Z Message: Could not start container nextcloud-aio-nextcloud: Server error: `POST http://127.0.0.1/v1.41/containers/nextcloud-aio-nextcloud/start` resulted in a `500 Internal Server Error` response:
2024-09-14T10:35:42.954438982Z {"message":"error gathering device information while adding custom device \"/dev/dri\": no such file or directory"}
2024-09-14T10:35:42.954450882Z File: /var/www/docker-aio/php/src/Docker/DockerActionManager.php
2024-09-14T10:35:42.954461883Z Line: 192
2024-09-14T10:35:42.954472383Z Trace: #0 /var/www/docker-aio/php/src/Controller/DockerController.php(66): AIO\Docker\DockerActionManager->StartContainer(Object(AIO\Container\Container))
2024-09-14T10:35:42.954484684Z #1 /var/www/docker-aio/php/src/Controller/DockerController.php(33): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-n...', true)
2024-09-14T10:35:42.954496184Z #2 /var/www/docker-aio/php/src/Controller/DockerController.php(211): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-a...', true)
2024-09-14T10:35:42.954507385Z #3 /var/www/docker-aio/php/src/Controller/DockerController.php(191): AIO\Controller\DockerController->startTopContainer(true)
2024-09-14T10:35:42.954534586Z #4 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): AIO\Controller\DockerController->StartContainer(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
2024-09-14T10:35:42.954546386Z #5 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(363): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
2024-09-14T10:35:42.954556387Z #6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:35:42.954565487Z #7 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:35:42.954574388Z #8 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(321): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:35:42.954586388Z #9 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(74): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:35:42.954595889Z #10 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(482): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:35:42.954604789Z #11 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(177): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
2024-09-14T10:35:42.954613989Z #12 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:35:42.954622990Z #13 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-09-14T10:35:42.954632590Z #14 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:35:42.954641791Z #15 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(280): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-09-14T10:35:42.954650991Z #16 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:35:42.954660191Z #17 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-09-14T10:35:42.954669692Z #18 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:35:42.954678592Z #19 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(209): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:35:42.954695093Z #20 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(193): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:35:42.954704893Z #21 /var/www/docker-aio/php/public/index.php(185): Slim\App->run()
2024-09-14T10:35:42.954713794Z #22 {main}
2024-09-14T10:35:42.954723794Z Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
2024-09-14T10:39:34.019647635Z NOTICE: PHP message: Slim Application Error
2024-09-14T10:39:34.019676636Z Type: GuzzleHttp\Exception\ClientException
2024-09-14T10:39:34.019683336Z Code: 404
2024-09-14T10:39:34.019688837Z Message: Client error: `GET http://127.0.0.1/v1.41/containers/nextcloud-aio-apache/logs?stdout=true&stderr=true&timestamps=true` resulted in a `404 Not Found` response:
2024-09-14T10:39:34.019694637Z {"message":"No such container: nextcloud-aio-apache"}
2024-09-14T10:39:34.019699837Z File: /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php
2024-09-14T10:39:34.019705037Z Line: 111
2024-09-14T10:39:34.019709938Z Trace: #0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
2024-09-14T10:39:34.019715538Z #1 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
2024-09-14T10:39:34.019720738Z #2 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
2024-09-14T10:39:34.019726338Z #3 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
2024-09-14T10:39:34.019731839Z #4 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
2024-09-14T10:39:34.019737039Z #5 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
2024-09-14T10:39:34.019742239Z #6 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
2024-09-14T10:39:34.019747339Z #7 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
2024-09-14T10:39:34.019752439Z #8 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
2024-09-14T10:39:34.019757740Z #9 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Promise\Promise->wait()
2024-09-14T10:39:34.019762940Z #10 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request('GET', 'http://127.0.0....', Array)
2024-09-14T10:39:34.019768240Z #11 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(172): GuzzleHttp\Client->get('http://127.0.0....')
2024-09-14T10:39:34.019787641Z #12 /var/www/docker-aio/php/src/Controller/DockerController.php(74): AIO\Docker\DockerActionManager->GetLogs('nextcloud-aio-a...')
2024-09-14T10:39:34.019795941Z #13 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): AIO\Controller\DockerController->GetLogs(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
2024-09-14T10:39:34.019800742Z #14 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(363): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
2024-09-14T10:39:34.019805242Z #15 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.019809542Z #16 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.019813742Z #17 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(321): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.019817942Z #18 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(74): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.019822043Z #19 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(482): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.019826243Z #20 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(177): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
2024-09-14T10:39:34.019830743Z #21 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.019835143Z #22 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-09-14T10:39:34.019839643Z #23 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.019844844Z #24 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(280): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-09-14T10:39:34.019849344Z #25 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.019853644Z #26 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-09-14T10:39:34.019858044Z #27 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.019866344Z #28 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(209): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.019870945Z #29 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(193): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.019875545Z #30 /var/www/docker-aio/php/public/index.php(185): Slim\App->run()
2024-09-14T10:39:34.019879545Z #31 {main}
2024-09-14T10:39:34.019883245Z Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
2024-09-14T10:39:34.424476075Z NOTICE: PHP message: 404 Not Found
2024-09-14T10:39:34.424497376Z Type: Slim\Exception\HttpNotFoundException
2024-09-14T10:39:34.424501176Z Code: 404
2024-09-14T10:39:34.424503977Z Message: Not found.
2024-09-14T10:39:34.424506977Z File: /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
2024-09-14T10:39:34.424509877Z Line: 76
2024-09-14T10:39:34.424512877Z Trace: #0 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(62): Slim\Middleware\RoutingMiddleware->performRouting(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.424516277Z #1 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(482): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.424519477Z #2 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(177): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
2024-09-14T10:39:34.424522977Z #3 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.424526378Z #4 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-09-14T10:39:34.424529678Z #5 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.424532878Z #6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(280): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-09-14T10:39:34.424536578Z #7 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.424539778Z #8 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-09-14T10:39:34.424543678Z #9 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.424553879Z #10 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(209): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.424556379Z #11 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(193): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-09-14T10:39:34.424558679Z #12 /var/www/docker-aio/php/public/index.php(185): Slim\App->run()
2024-09-14T10:39:34.424560779Z #13 {main}
2024-09-14T10:39:34.424562879Z Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.

**Comment by szaimen** [comment]
> "error gathering device information while adding custom device "/dev/dri": no such file or directory

This is your issue. See the warning here: https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-enable-hardware-transcoding-for-nextcloud
