### ISSUE TITLE
Could not start container nextcloud-aio-caddy

### ISSUE THREAD

**Issue by laurentperrinet** [nextcloud/all-in-one#5744]
My long-running setup recently stopped working. 

### Steps to reproduce
1. my NC AIO instance runs constantly 
2. after a backup it stopped working
3. tried everything I could on the gitHub to fix it but to no avail

### Actual behavior

* the mastercontainer could not start. log:

```
2024-12-13T09:59:31.182614261Z Trying to fix docker.sock permissions internally...
2024-12-13T09:59:31.185983234Z Creating docker group internally with id 994
2024-12-13T09:59:31.570551631Z [0;92mInitial startup of Nextcloud All-in-One complete!
2024-12-13T09:59:31.570579615Z You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
2024-12-13T09:59:31.570583905Z E.g. https://internal.ip.of.this.server:8080
2024-12-13T09:59:31.570587089Z ⚠️ Important: do always use an ip-address if you access this port and not a domain as HSTS might block access to it later!
2024-12-13T09:59:31.570590999Z 
2024-12-13T09:59:31.570593921Z If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
2024-12-13T09:59:31.570597335Z https://your-domain-that-points-to-this-server.tld:8443[0m
2024-12-13T09:59:32.834991794Z ++ head -1 /mnt/docker-aio-config/data/daily_backup_time
2024-12-13T09:59:32.835559481Z + BACKUP_TIME=02:00
2024-12-13T09:59:32.835575192Z + export BACKUP_TIME
2024-12-13T09:59:32.835578346Z + export DAILY_BACKUP=1
2024-12-13T09:59:32.835580401Z + DAILY_BACKUP=1
2024-12-13T09:59:32.839551884Z ++ sed -n 2p /mnt/docker-aio-config/data/daily_backup_time
2024-12-13T09:59:32.840065049Z + '[' '' '!=' automaticUpdatesAreNotEnabled ']'
2024-12-13T09:59:32.840073111Z + export AUTOMATIC_UPDATES=1
2024-12-13T09:59:32.840075453Z + AUTOMATIC_UPDATES=1
2024-12-13T09:59:32.841543492Z ++ sed -n 3p /mnt/docker-aio-config/data/daily_backup_time
2024-12-13T09:59:32.842684848Z + '[' '' '!=' successNotificationsAreNotEnabled ']'
2024-12-13T09:59:32.842696734Z + export SEND_SUCCESS_NOTIFICATIONS=1
2024-12-13T09:59:32.842699419Z + SEND_SUCCESS_NOTIFICATIONS=1
2024-12-13T09:59:32.842701479Z + set +x
2024-12-13T09:59:32.870589094Z [Fri Dec 13 09:59:32.870304 2024] [mpm_event:notice] [pid 145:tid 145] AH00489: Apache/2.4.62 (Unix) OpenSSL/3.3.2 configured -- resuming normal operations
2024-12-13T09:59:32.870610112Z [Fri Dec 13 09:59:32.870341 2024] [core:notice] [pid 145:tid 145] AH00094: Command line: 'httpd -D FOREGROUND'
2024-12-13T09:59:32.878618136Z [13-Dec-2024 09:59:32] NOTICE: fpm is running, pid 150
2024-12-13T09:59:32.878634260Z [13-Dec-2024 09:59:32] NOTICE: ready to handle connections
2024-12-13T09:59:32.885698377Z {"level":"info","ts":1734083972.8854828,"msg":"using config from file","file":"/Caddyfile"}
2024-12-13T09:59:32.887015893Z {"level":"info","ts":1734083972.8868635,"msg":"adapted config to JSON","adapter":"caddyfile"}
2024-12-13T09:59:51.998081687Z NOTICE: PHP message: Slim Application Error
2024-12-13T09:59:51.998102699Z Type: Exception
2024-12-13T09:59:51.998106226Z Code: 0
2024-12-13T09:59:51.998108841Z Message: Could not start container nextcloud-aio-caddy: Server error: `POST http://127.0.0.1/v1.41/containers/nextcloud-aio-caddy/start` resulted in a `500 Internal Server Error` response:
2024-12-13T09:59:51.998120717Z {"message":"driver failed programming external connectivity on endpoint nextcloud-aio-caddy (acc8fc7a94460c035b6832b6381 (truncated...)
2024-12-13T09:59:51.998124036Z File: /var/www/docker-aio/php/src/Docker/DockerActionManager.php
2024-12-13T09:59:51.998126109Z Line: 170
2024-12-13T09:59:51.998128040Z Trace: #0 /var/www/docker-aio/php/src/Controller/DockerController.php(59): AIO\Docker\DockerActionManager->StartContainer(Object(AIO\Container\Container))
2024-12-13T09:59:51.998130755Z #1 /var/www/docker-aio/php/src/Controller/DockerController.php(26): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-c...', true)
2024-12-13T09:59:51.998133155Z #2 /var/www/docker-aio/php/src/Controller/DockerController.php(209): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-a...', true)
2024-12-13T09:59:51.998135395Z #3 /var/www/docker-aio/php/src/Controller/DockerController.php(189): AIO\Controller\DockerController->startTopContainer(true)
2024-12-13T09:59:51.998137609Z #4 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): AIO\Controller\DockerController->StartContainer(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
2024-12-13T09:59:51.998140089Z #5 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(363): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
2024-12-13T09:59:51.998142840Z #6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-12-13T09:59:51.998145183Z #7 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-12-13T09:59:51.998147406Z #8 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(321): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-12-13T09:59:51.998150889Z #9 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(74): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
2024-12-13T09:59:51.998153343Z #10 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(482): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-12-13T09:59:51.998155597Z #11 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(177): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
2024-12-13T09:59:51.998158090Z #12 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(117): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-12-13T09:59:51.998160519Z #13 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-12-13T09:59:51.998163067Z #14 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(36): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-12-13T09:59:51.998167917Z #15 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(280): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-12-13T09:59:51.998170517Z #16 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-12-13T09:59:51.998172832Z #17 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
2024-12-13T09:59:51.998175310Z #18 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-12-13T09:59:51.998177609Z #19 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(209): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-12-13T09:59:51.998179818Z #20 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(193): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
2024-12-13T09:59:51.998182252Z #21 /var/www/docker-aio/php/public/index.php(188): Slim\App->run()
2024-12-13T09:59:51.998184447Z #22 {main}
2024-12-13T09:59:51.998186731Z Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
```

#### Host OS 

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

```

#### Output of `sudo docker info`

```
$ sudo docker info
Client: Docker Engine - Community
 Version:    27.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 22
  Running: 1
  Paused: 0
  Stopped: 21
 Images: 36
 Server Version: 27.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-50-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 39.1GiB
 Name: babbage
 ID: 1d273c00-86db-42a0-818b-a625004d29c9
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

#### Docker run command or docker-compose file that you used

```

docker run \
--init \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 8080:8080 \
--env APACHE_PORT=11000 \
--env APACHE_IP_BINDING=0.0.0.0 \
--env APACHE_IP_BINDING=127.0.0.1 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
--env AIO_COMMUNITY_CONTAINERS="caddy facerecognition fail2ban local-ai memories libretranslate" \
--env NEXTCLOUD_DATADIR=/data/nc-aio \
nextcloud/all-in-one:latest



```

**Comment by szaimen** [comment]
Hi, can you post the output of `sudo netstat -tulpn` here?
