### ISSUE TITLE
changed datadir - Internal server error

### ISSUE THREAD

**Issue by sim-san** [nextcloud/all-in-one#656]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. create the folder /mnt/ncdata and mount a blobfuse on this folder
2. change owner and mod as described here: https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
3. start the AIO master container

### Actual behavior 
I got the following error in the log:
```
Server error: `POST http://localhost/v1.41/containers/nextcloud-aio-nextcloud/start` resulted in a `500 Internal Server Error` response:\n{&quot;message&quot;:&quot;error while creating mount source path '/mnt/ncdata': mkdir /mnt/ncdata: file exists
```

### Host OS 
Ubuntu 20.04

#### Nextcloud AIO version 
1.2.0

#### Current channel 
latest

#### Other valuable info 
Command:
`sudo docker run -d --name nextcloud-aio-mastercontainer --restart always -p 80:80 -p 8080:8080 -p 8443:8443 -e NEXTCLOUD_DATADIR="/mnt/ncdata" --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock:ro nextcloud/all-in-one:latest`
Logs:
```
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 998
[0;92mInitial startup of Nextcloud All In One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080

If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatially by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443[0m
2022-05-18 18:57:32,176 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
{"level":"info","ts":1652900253.240866,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
{"level":"warn","ts":1652900253.2424617,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/Caddyfile","line":2}
{"level":"info","ts":1652900253.2436533,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"warn","ts":1652900253.244045,"logger":"http","msg":"automatic HTTP->HTTPS redirects are disabled","server_name":"srv0"}
{"level":"warn","ts":1652900253.2444365,"logger":"tls","msg":"YOUR SERVER MAY BE VULNERABLE TO ABUSE: on-demand TLS is enabled, but no protections are in place","docs":"https://caddyserver.com/docs/automatic-https#on-demand-tls"}
{"level":"error","ts":1652900253.2447953,"msg":"unable to create folder for config autosave","dir":"/var/www/.config/caddy","error":"mkdir /var/www/.config: permission denied"}
{"level":"info","ts":1652900253.2450318,"msg":"serving initial configuration"}
{"level":"info","ts":1652900253.2453141,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00044ad20"}
{"level":"info","ts":1652900253.2455485,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/docker-aio-config/caddy/"}
{"level":"info","ts":1652900253.2480376,"logger":"tls","msg":"finished cleaning storage units"}
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Wed May 18 18:57:33.255452 2022] [ssl:warn] [pid 96] AH01906: 172.17.0.2:8080:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed May 18 18:57:33.255502 2022] [ssl:warn] [pid 96] AH01909: 172.17.0.2:8080:0 server certificate does NOT include an ID which matches the server name
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Wed May 18 18:57:33.279236 2022] [ssl:warn] [pid 96] AH01906: 172.17.0.2:8080:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed May 18 18:57:33.279260 2022] [ssl:warn] [pid 96] AH01909: 172.17.0.2:8080:0 server certificate does NOT include an ID which matches the server name
[Wed May 18 18:57:33.282138 2022] [mpm_prefork:notice] [pid 96] AH00163: Apache/2.4.53 (Debian) PHP/8.0.18 OpenSSL/1.1.1n configured -- resuming normal operations
[Wed May 18 18:57:33.282433 2022] [core:notice] [pid 96] AH00094: Command line: 'apache2 -D FOREGROUND'
172.17.0.2:8000 localhost - - [18/May/2022:18:57:43 +0000] "GET / HTTP/1.1" 302 309 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
localhost - - [18/May/2022:18:57:43 +0000] "GET / HTTP/1.1" 302 309 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
172.17.0.2:8000 localhost - - [18/May/2022:18:57:44 +0000] "GET /containers HTTP/1.1" 200 2470 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
localhost - - [18/May/2022:18:57:44 +0000] "GET /containers HTTP/1.1" 200 2470 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
172.17.0.2:8000 localhost - - [18/May/2022:18:58:17 +0000] "POST /api/docker/stop HTTP/1.1" 201 301 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
localhost - - [18/May/2022:18:58:17 +0000] "POST /api/docker/stop HTTP/1.1" 201 301 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
172.17.0.2:8000 localhost - - [18/May/2022:18:58:20 +0000] "GET / HTTP/1.1" 302 309 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
localhost - - [18/May/2022:18:58:20 +0000] "GET / HTTP/1.1" 302 309 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
172.17.0.2:8000 localhost - - [18/May/2022:18:58:20 +0000] "GET /containers HTTP/1.1" 200 2283 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
localhost - - [18/May/2022:18:58:20 +0000] "GET /containers HTTP/1.1" 200 2283 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
[Wed May 18 18:58:43.336671 2022] [php:notice] [pid 128] [client 127.0.0.1:48762] Slim Application Error\nType: GuzzleHttp\\Exception\\ServerException\nCode: 500\nMessage: Server error: `POST http://localhost/v1.41/containers/nextcloud-aio-nextcloud/start` resulted in a `500 Internal Server Error` response:\n{&quot;message&quot;:&quot;error while creating mount source path '/mnt/ncdata': mkdir /mnt/ncdata: file exists&quot;}\n\n\nFile: /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php\nLine: 113\nTrace: #0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response), NULL, Array, NULL)\n#1 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))\n#2 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), NULL)\n#3 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()\n#4 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Promise\\TaskQueue->run(true)\n#5 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()\n#6 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#7 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()\n#8 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#9 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Promise\\Promise->wait()\n#10 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\\Client->request('POST', 'http://localhos...', Array)\n#11 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(177): GuzzleHttp\\Client->post('http://localhos...')\n#12 /var/www/docker-aio/php/src/Controller/DockerController.php(50): AIO\\Docker\\DockerActionManager->StartContainer(Object(AIO\\Container\\Container))\n#13 /var/www/docker-aio/php/src/Controller/DockerController.php(33): AIO\\Controller\\DockerController->PerformRecursiveContainerStart('nextcloud-aio-n...')\n#14 /var/www/docker-aio/php/src/Controller/DockerController.php(160): AIO\\Controller\\DockerController->PerformRecursiveContainerStart('nextcloud-aio-a...')\n#15 /var/www/docker-aio/php/src/Controller/DockerController.php(144): AIO\\Controller\\DockerController->startTopContainer()\n#16 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): AIO\\Controller\\DockerController->StartContainer(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(GuzzleHttp\\Psr7\\Response), Array)\n#17 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(GuzzleHttp\\Psr7\\ServerRequest), Object(GuzzleHttp\\Psr7\\Response), Array)\n#18 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\\Routing\\Route->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#19 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\\MiddlewareDispatcher->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#20 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\\MiddlewareDispatcher->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#21 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\\Routing\\Route->run(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#22 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(456): Slim\\Routing\\RouteRunner->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#23 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): Slim\\Csrf\\Guard->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Slim\\Routing\\RouteRunner))\n#24 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#25 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\\Views\\TwigMiddleware->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#26 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#27 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): AIO\\Middleware\\AuthMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#28 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#29 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#30 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#31 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(215): Slim\\MiddlewareDispatcher->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#32 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\\App->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#33 /var/www/docker-aio/php/public/index.php(155): Slim\\App->run()\n#34 {main}, referer: https://nextcloud.stadtmission-arheilgen.de:8443/containers
172.17.0.2:8000 localhost - - [18/May/2022:18:58:34 +0000] "POST /api/docker/start HTTP/1.1" 500 6901 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
localhost - - [18/May/2022:18:58:34 +0000] "POST /api/docker/start HTTP/1.1" 500 6901 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
172.17.0.2:8000 localhost - - [18/May/2022:18:58:52 +0000] "GET /api/docker/logs?id=nextcloud-aio-mastercontainer HTTP/1.1" 200 3222 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
localhost - - [18/May/2022:18:58:52 +0000] "GET /api/docker/logs?id=nextcloud-aio-mastercontainer HTTP/1.1" 200 3222 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
172.17.0.2:8000 localhost - - [18/May/2022:19:08:07 +0000] "GET /api/docker/logs?id=nextcloud-aio-mastercontainer HTTP/1.1" 200 3263 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
localhost - - [18/May/2022:19:08:07 +0000] "GET /api/docker/logs?id=nextcloud-aio-mastercontainer HTTP/1.1" 200 3263 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
172.17.0.2:8000 localhost - - [18/May/2022:19:08:09 +0000] "GET /api/docker/logs?id=nextcloud-aio-nextcloud HTTP/1.1" 200 314 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
localhost - - [18/May/2022:19:08:09 +0000] "GET /api/docker/logs?id=nextcloud-aio-nextcloud HTTP/1.1" 200 314 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
172.17.0.2:8000 localhost - - [18/May/2022:19:08:12 +0000] "GET /containers HTTP/1.1" 200 2470 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
localhost - - [18/May/2022:19:08:12 +0000] "GET /containers HTTP/1.1" 200 2470 "https://nextcloud.stadtmission-arheilgen.de:8443/containers" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
```

**Comment by sim-san** [comment]
I asked me, why it's run this command:
`mkdir /mnt/ncdata`

Iis it a bad decision to have the same path for the datadir folder outside the docker like inside the docker image ? Should I change the path ?

**Comment by sim-san** [comment]
I also test it without the mount of blobfuse.
So I delete all docker images, containers, volumes. It still does not work. I get the following error on the nextcloud container:
`Appdata is not present. Did you maybe change the datadir after aio was first started?`

**Comment by szaimen** [comment]
Hello, how did you install docker? Did you use the recommended script or maybe `sudo snap install docker`?

**Comment by sim-san** [comment]
I use the recommend script from get.docker.com

**Comment by szaimen** [comment]
All right...

Let me google this then...

**Comment by szaimen** [comment]
Okay, this might be an imcompatibility issue with blobfuse and docker mounts...

If you mounted the blobfuse in `/mnt/ncdata`, can you try to add a subdir like `/mnt/ncdata/data` as NEXTCLOUD_DATADIR? e.g. `-e NEXTCLOUD_DATADIR="/mnt/ncdata/data" (and obviously apply the correct permissions before).

Does this work?

**Comment by sim-san** [comment]
I will test it tomorrow. But my second test without blobfuse should work?

**Comment by szaimen** [comment]
> I will test it tomorrow. But my second test without blobfuse should work?

yes but you probably did not correctly remove all containers and volumes...

**Comment by sim-san** [comment]
How can I delete all container and volumes for a clean setup ?

**Comment by szaimen** [comment]
try this: https://github.com/nextcloud/all-in-one/discussions/565#discussioncomment-2718055

**Comment by sim-san** [comment]
> Okay, this might be an imcompatibility issue with blobfuse and docker mounts...
> 
> If you mounted the blobfuse in `/mnt/ncdata`, can you try to add a subdir like `/mnt/ncdata/data` as NEXTCLOUD_DATADIR? e.g. `-e NEXTCLOUD_DATADIR="/mnt/ncdata/data"` (and obviously apply the correct permissions before).
> 
> Does this work?

I get an new error. I also canged the path away from /mnt/ncdata to /fuse/stnextcloud/ncdata. I create an folder `data` and specify: `-e NEXTCLOUD_DATADIR="/fuse/stnextcloud/ncdata/data"`

Error:
`500 Internal Server Error response:\n{&quot;message&quot;:&quot;error while creating mount source path '/fuse/stnextcloud/ncdata/data': mkdir /fuse/stnextcloud/ncdata: file (truncated...)`

**Comment by szaimen** [comment]
Hm... Do you have a `/etc/fuse.conf` file on your host? You may also search for it like this: `sudo find /etc -name fuse.conf`. Then please send me the outout of `sudo cat /etc/fuse.conf`. Thanks!

**Comment by sim-san** [comment]
cat /etc/fuse.conf
```
# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#mount_max = 1000

# Allow non-root users to specify the allow_other or allow_root mount options.
#user_allow_other
```

**Comment by sim-san** [comment]
> Can you uncomment `#user_allow_other` so that it gets activated, restart your system and try again?

This solves the first part of the problems. After 2 hours it works. I will create an toutorial how to setup Nextcloud AOI with Azure Blob Storage using blobfuse, 

maybe we can link this here ?
