### ISSUE TITLE
Backup successful but not visible in the AIO mastercontainer

### ISSUE THREAD

**Issue by manugch** [nextcloud/all-in-one#762]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have running AIO instance
2. Perform backup

### Expected behavior 
Show available restore points after backup.

### Actual behavior 
AIO mastercontainer is not able to list past backups.

### Host OS 
Ubuntu 20.04

#### Nextcloud AIO version 
1.3.1

#### Current channel 
latest

#### Other valuable info 
As you can see the AIO container is not aware when the backup was done nor that there even is one.
![image](https://user-images.githubusercontent.com/5999772/170947313-b6d6650e-55bc-4e85-b414-fbc434d2e0f8.png)

Does the mastercontainer has it's own backup database or does it just work by directly accessing the files in the backup folder?

**Comment by szaimen** [comment]
Hello, can you show the logs of the last backup? (Click on logs right next to backup was successful)

**Comment by manugch** [comment]
Hi
Yes sure
`Breaking the borg lock...
Performing backup...
Starting the backup...
0 B O 0 B C 0 B D 0 N nextcloud_aio_volumes                                     
zing cache transaction: Reading config
zing cache transaction: Reading chunks
zing cache transaction: Reading files
 O 23.56 MB C 2.57 kB D 1077 N nextcloud_aio_vol...in/x86_64/notify_push
 O 28.59 MB C 5.58 kB D 2073 N nextcloud_aio_vol...sitionalParameter.php
 O 29.13 MB C 5.58 kB D 2484 N nextcloud_aio_vol...mportExportClient.php
 O 29.41 MB C 5.58 kB D 2825 N nextcloud_aio_vol...src/Emr/EmrClient.php
 O 29.61 MB C 5.58 kB D 3145 N nextcloud_aio_vol...-05-30/api-2.json.php
B O 30.48 MB C 5.58 kB D 3465 N nextcloud_aio_vol...aginators-1.json.php
B O 31.50 MB C 5.58 kB D 3780 N nextcloud_aio_vol...03-01/api-2.json.php
B O 32.30 MB C 5.58 kB D 4172 N nextcloud_aio_vol...ocale/data/en-pn.php
B O 33.03 MB C 5.58 kB D 4655 N nextcloud_aio_vol...rier/data/en/968.php
B O 33.48 MB C 5.58 kB D 5140 N nextcloud_aio_vol...umberMetadata_NF.php
B O 35.80 MB C 5.58 kB D 5541 N nextcloud_aio_vol...MessageFormatter.php
B O 36.46 MB C 5.58 kB D 6018 N nextcloud_aio_vol...aryOp/LogicalAnd.php
B O 37.46 MB C 5.58 kB D 6478 N nextcloud_aio_vol.../en-IN/calendar.json
B O 38.50 MB C 5.58 kB D 6942 N nextcloud_aio_vol...ismatchException.php
B O 39.30 MB C 5.58 kB D 7447 N nextcloud_aio_vol...sses/Swift/Spool.php
B O 40.32 MB C 5.58 kB D 7947 N nextcloud_aio_vol...tor/PhpExtractor.php
B O 40.78 MB C 5.58 kB D 8380 N nextcloud_aio_vol...adBalancerMember.php
B O 52.25 MB C 281.77 kB D 8794 N nextcloud_aio_vo...s/code_signing.html
B O 69.86 MB C 689.21 kB D 9222 N nextcloud_aio_vo...e20201111081915.php
B O 78.57 MB C 2.37 MB D 9512 N nextcloud_aio_vol...core/js/dist/main.js
B O 86.92 MB C 8.65 MB D 9664 N nextcloud_aio_vol...Nextcloud Manual.pdf
B O 107.32 MB C 18.91 MB D 9934 N nextcloud_aio_vo...loud/lib/l10n/ug.js
B O 108.38 MB C 19.02 MB D 10531 N nextcloud_aio_v.../Remote/Api/OCS.php
B O 109.15 MB C 19.03 MB D 11094 N nextcloud_aio_v...stractNodeEvent.php
B O 111.85 MB C 19.16 MB D 11514 N nextcloud_aio_v...assword_policy/l10n
B O 119.00 MB C 19.74 MB D 11813 N nextcloud_aio_v...t/js/text-public.js
B O 122.01 MB C 21.76 MB D 12137 N nextcloud_aio_v...highlight/scilab.js
B O 123.43 MB C 22.00 MB D 12596 N nextcloud_aio_v.../activity/__mocks__
B O 126.12 MB C 22.31 MB D 13005 N nextcloud_aio_v...ib/IAuditLogger.php
B O 127.24 MB C 22.73 MB D 13452 N nextcloud_aio_v...erfaceException.php
B O 129.12 MB C 22.74 MB D 13897 N nextcloud_aio_v...mments/l10n/nb.json
B O 145.51 MB C 22.89 MB D 14238 N nextcloud_aio_v...apps/dav/l10n/de.js
B O 146.51 MB C 23.23 MB D 14753 N nextcloud_aio_v...cryption/l10n/fa.js
B O 147.25 MB C 23.48 MB D 15232 N nextcloud_aio_v...deration/l10n/sl.js
B O 150.75 MB C 24.11 MB D 15652 N nextcloud_aio_v...lScriptsAdapter.php
B O 153.31 MB C 24.59 MB D 16139 N nextcloud_aio_v...build/pdf.worker.js
B O 157.65 MB C 24.60 MB D 16535 N nextcloud_aio_v...ghtclick/l10n/de.js
B O 160.49 MB C 25.15 MB D 16922 N nextcloud_aio_v...ng/l10n/sr@latin.js
B O 161.18 MB C 25.25 MB D 17417 N nextcloud_aio_v...versions/l10n/ja.js
B O 165.94 MB C 25.76 MB D 17825 N nextcloud_aio_v...reader/l10n/bs.json
B O 166.53 MB C 25.81 MB D 18283 N nextcloud_aio_v...h2/js/oauth2.js.map
B O 170.07 MB C 25.90 MB D 18672 N nextcloud_aio_v...ivacy/composer.lock
B O 172.85 MB C 26.40 MB D 19077 N nextcloud_aio_v...erinfo/l10n/gl.json
B O 181.70 MB C 27.35 MB D 19329 N nextcloud_aio_v...tings/l10n/es_NI.js
B O 183.59 MB C 28.53 MB D 19777 N nextcloud_aio_v...ps/survey_client/js
B O 184.39 MB C 28.81 MB D 20274 N nextcloud_aio_v...nd/UpdateConfig.php
B O 185.86 MB C 29.39 MB D 20711 N nextcloud_aio_v...r_ldap/l10n/nl.json
B O 190.15 MB C 30.84 MB D 21023 N nextcloud_aio_v.../viewer-main.js.map
B O 193.01 MB C 32.07 MB D 21353 N nextcloud_aio_v...rkflowengine.js.map
B O 196.47 MB C 32.23 MB D 21540 N nextcloud_aio_v...20201210_180847.jpg
.....
B O 525.84 GB C 1.17 GB D 174747 N nextcloud_aio_v...001000000020000002C
B O 525.85 GB C 1.17 GB D 175583 N nextcloud_aio_v...se/base/16384/16800
B O 525.86 GB C 1.18 GB D 175583 N nextcloud_aio_v...se/base/16384/16800
B O 525.86 GB C 1.18 GB D 175583 N nextcloud_aio_v...se/base/16384/16800
B O 525.87 GB C 1.19 GB D 176167 N nextcloud_aio_v...se/base/16384/17910
B O 525.88 GB C 1.20 GB D 176312 N nextcloud_aio_v...se/base/16384/18124
B O 525.89 GB C 1.20 GB D 176316 N nextcloud_aio_v...se/base/16384/18130
B O 525.90 GB C 1.21 GB D 176765 N nextcloud_aio_v...p/database-dump.sql
B O 525.91 GB C 1.22 GB D 176765 N nextcloud_aio_v...p/database-dump.sql
B O 525.91 GB C 1.22 GB D 176765 N nextcloud_aio_v...p/database-dump.sql
ng segments   0%
ng segments  25%
ng segments  50%
ng segments  75%
iles cache
hunks cache
ache config
                                                                        
----------------------------------------------------------------------
Archive name: 20220530_075134-nextcloud-aio
Archive fingerprint: e2ee566ea95d1937573ff9299868ab5e0da7d054ef4511f5c7b511a352f1403d
Time (start): Mon, 2022-05-30 07:51:34
Time (end):   Mon, 2022-05-30 07:58:20
Duration: 6 minutes 45.88 seconds
Number of files: 176766
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              540.06 GB            525.92 GB              1.22 GB
All archives:                3.20 TB              3.11 TB            513.51 GB

                       Unique chunks         Total chunks
Chunk index:                  365875              2190291
------------------------------------------------------------------------------
Pruning the archives...

----------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:                3.20 TB              3.11 TB            513.51 GB

                       Unique chunks         Total chunks
Chunk index:                  365875              2190291
------------------------------------------------------------------------------
Backup finished successfully on 30.05.2022 - 07:58:22 (00 hours 06 minutes 48 seconds)
`
(I've removed the logs of the private files)

**Comment by szaimen** [comment]
Basically the internal database should be updated on every backup container execution... (Check backup, create backup, restore backup...)

**Comment by manugch** [comment]
`Backup finished successfully on 30.05.2022 - 07:58:22 (00 hours 06 minutes 48 seconds)`
Is actually the last line of the log (i didn't cut anything there).
The lines I removed where just the list of files being backuped which i replaced with ".....". (they can't be relevant for this)

**Comment by szaimen** [comment]
I see and probably the points are still not listed kn the aio interface?

**Comment by szaimen** [comment]
Is anything written to this file? `/var/lib/docker/volumes/nextcloud_aio_mastercontainer/_data/data/backup_archives.list`

**Comment by manugch** [comment]
> I see and probably the points are still not listed kn the aio interface?
No still nothing there


> Is anything written to this file? `/var/lib/docker/volumes/nextcloud_aio_mastercontainer/_data/data/backup_archives.list`
The file is completely empty but shows a modified file timestamp which is equal to the backup time.

**Comment by szaimen** [comment]
Thanks! Can you do this and post the output of it here please?

```
# Install borgbackup on the host
sudo apt update && sudo apt install borgbackup

# List all archives (if you are using the default backup location /mnt/backup/borg)
sudo borg list "/mnt/backup/borg"
```

**Comment by manugch** [comment]
Sure 

```
nc@nextcloud02:~$ sudo apt update && sudo apt install borgbackup
[sudo] password for nc:
Hit:1 http://ch.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://ch.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://ch.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://ch.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://download.docker.com/linux/ubuntu focal InRelease
Ign:6 http://download.webmin.com/download/repository sarge InRelease
Hit:7 http://download.webmin.com/download/repository sarge Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
borgbackup is already the newest version (1.1.15-1~ubuntu1.20.04.1).
The following package was automatically installed and is no longer required:
  libfwupdplugin1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
nc@nextcloud02:~$ sudo borg list "/mnt/backup/borg"
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 162, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 356, in acquire
    self._roster.modify(SHARED, ADD)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 117, in __exit__
    self.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 150, in release
    os.rmdir(self.path)
OSError: [Errno 39] Directory not empty: '/mnt/backup/borg/lock.exclusive'

Platform: Linux nextcloud02 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64
Linux: Unknown Linux
Borg: 1.1.15  Python: CPython 3.8.10 msgpack: 0.5.6
PID: 2029047  CWD: /home/nc
sys.argv: ['/usr/bin/borg', 'list', '/mnt/backup/borg']
SSH_ORIGINAL_COMMAND: None
```

**Comment by szaimen** [comment]
On what type of mount is the backup created on? On an directly connwcted drive or smb/nfs moubt, other?

**Comment by manugch** [comment]
That's an nfs v4 mount

**Comment by szaimen** [comment]
I see. So somehow borg does not remove the borg lock correctly which is nothing we have control over. Does the integrity check work?

**Comment by manugch** [comment]
Yes the integrity check did work when i ran it a few days ago.

**Comment by szaimen** [comment]
> Should I remove the lock manually?

You can try by running `sudo borg break-lock /mnt/backup/borg` and see if the borg list command works afterwards.

**Comment by manugch** [comment]
> > Should I remove the lock manually?
> 
> You can try by running `sudo borg break-lock /mnt/backup/borg` and see if the borg list command works afterwards.

I did run the break-lock command and then borg list again but the exception is still thrown. 
Seems like the lock.exclusive was not removed.
```
sudo borg break-lock /mnt/backup/borg --debug
using builtin fallback logging configuration
35 self tests completed in 0.06 seconds
```


```
sudo borg list "/mnt/backup/borg"
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 162, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 356, in acquire
    self._roster.modify(SHARED, ADD)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 117, in __exit__
    self.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 150, in release
    os.rmdir(self.path)
OSError: [Errno 39] Directory not empty: '/mnt/backup/borg/lock.exclusive'

Platform: Linux nextcloud02 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64
Linux: Unknown Linux
Borg: 1.1.15  Python: CPython 3.8.10 msgpack: 0.5.6
PID: 2042964  CWD: /home/nc
sys.argv: ['/usr/bin/borg', 'list', '/mnt/backup/borg']
SSH_ORIGINAL_COMMAND: None
```

**Comment by szaimen** [comment]
> I could just delete the lock file manually.

you may try to rename it to a different name first which may also solve this problem...

**Comment by manugch** [comment]
> > I could just delete the lock file manually.
> 
> you may try to rename it to a different name first which may also solve this problem...

I did rename it, but as soon as i run "borg list" it is added again.

![image](https://user-images.githubusercontent.com/5999772/170966270-3a7bdb61-0802-48a7-a735-a8250d970edf.png)

**Comment by szaimen** [comment]
I think the lock.roster is also in the way... please rename both and try again.

**Comment by manugch** [comment]
> I think the lock.roster is also in the way... please rename both and try again.

Both files are immediately re added after the "borg list" command.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/5999772/170966989-485797e8-3161-4708-a80e-120c31ee6e16.png">

**Comment by manugch** [comment]
Yes still:

1. Rename files
2.
```
sudo borg list "/mnt/backup/borg"
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 162, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 356, in acquire
    self._roster.modify(SHARED, ADD)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 117, in __exit__
    self.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 150, in release
    os.rmdir(self.path)
OSError: [Errno 39] Directory not empty: '/mnt/backup/borg/lock.exclusive'

Platform: Linux nextcloud02 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64
Linux: Unknown Linux
Borg: 1.1.15  Python: CPython 3.8.10 msgpack: 0.5.6
PID: 2045942  CWD: /home/nc
sys.argv: ['/usr/bin/borg', 'list', '/mnt/backup/borg']
SSH_ORIGINAL_COMMAND: None
```
3. Files there again

**Comment by szaimen** [comment]
Can you please try to run the integrity check from the aio interface?

**Comment by szaimen** [comment]
Moving to discussions...
