### ISSUE TITLE
Slim application error when not using Docker tag 'latest' in imagename

### ISSUE THREAD

**Issue by dantefromhell** [nextcloud/all-in-one#813]
Ansible applies the 'latest' tag per default if not supplied in the image name [1].
If the tag was not supplied in the image name, it is not shown in the `Config.Image` output of `docker inspect $CONTAINER_NAME`.

After some digging into `docker inspect` it seems a more reliable way to retrieve the image tag could be:
1) Grab the `Image` hash from `docker inspect nextcloud-aio-mastercontainer`
2) Read the `RepoTags` variable from `docker image inspect $IMAGE_HASH`

The benefit of this solution would be that the tag is directly read from the image that is in use [2] 

[1] https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-image
[2] https://containers.gitbook.io/build-containers-the-hard-way/#manifest

### Steps to reproduce
1. Deploy nextcloud-aio using the following ansible snippet
```
  tasks:
    - name: Start 'nextcloud-all-in-one' container
      community.docker.docker_container:
        name:  nextcloud-aio-mastercontainer
        image: nextcloud/all-in-one
        state: started
        restart_policy: unless-stopped
        volumes:
          - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
          - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
          - "{{ ansible_default_ipv4.address }}:80:80"
          - "{{ ansible_default_ipv4.address }}:8443:8443"
          - "{{ ansible_default_ipv4.address }}:443:443"
```
3. Browse to `https://server-name:8443` and grab password
4. Log in, get error message

### Expected behavior 
The setup configuration dialog is shown

### Actual behavior 
After login, setup fails with the following stracktrace
```
Slim Application Error
Type: TypeError
Code: 0
Message: AIO\Docker\DockerActionManager::GetCurrentChannel(): Return value must be of type string, null returned
File: /var/www/docker-aio/php/src/Docker/DockerActionManager.php
Line: 434
Trace: #0 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(51): AIO\Docker\DockerActionManager->GetCurrentChannel()
#1 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(343): AIO\Docker\DockerActionManager->BuildImageName(Object(AIO\Container\Container))
#2 /var/www/docker-aio/php/src/Controller/DockerController.php(45): AIO\Docker\DockerActionManager->PullContainer(Object(AIO\Container\Container))
#3 /var/www/docker-aio/php/src/Controller/DockerController.php(224): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-d...')
#4 /var/www/docker-aio/php/public/index.php(72): AIO\Controller\DockerController->StartDomaincheckContainer()
#5 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Closure->{closure}(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#6 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#7 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#8 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#9 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#10 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
#11 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(456): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#12 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#13 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#14 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#15 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#16 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#17 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#18 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\MiddlewarerorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#19 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#20 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#21 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#22 /var/www/docker-aio/php/public/index.php(156): Slim\App->run()
#23 {main}
```

### Host OS 
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

#### Nextcloud AIO version 
Nextcloud AIO v1.3.1

**Comment by szaimen** [comment]
Honestly this is rather a feature request because using the latest tag as documented works.
However I will add some code that allows to use it even if no tag was provided.

**Comment by dantefromhell** [comment]
Pulling information from the wrong place and requiring the user to feed the information into the system via instructions IMO feels "buggy". 

Thx for adding patchwork though.
